친구 관련 기능 추가
Goal-Tracker/blooming-backend pull request #26
Opened 2023-12-18 14:57 UTC by JJ503

2023-12-22 08:01 UTC, jhsseonn requested changes
리뷰 늦게 드려 죄송합니다..!
저번 회의 때 논의했던 추가 컨벤션 사항까지 모두 확인했습니다.
수정할 부분보다는 로직이나 어노테이션 등 관련해서 궁금한 점 질문이 더 많은 것 같습니다.
그리고 말씀 주셨던 restDocs Description의 경우 저도 개행하지 않는 것이 더 가독성 있는 것 같아 개행하지 않는 것으로 진행하면 좋을 것 같습니다.

2023-12-23 05:30 UTC, JJ503 commented on src/main/java/com/backend/blooming/friend/domain/Friend.java
> +    @Id
적용했습니다!

2023-12-23 05:49 UTC, JJ503 commented on src/test/java/com/backend/blooming/friend/infrastructure/repository/FriendRepositoryTest.java
> +@Import(JpaConfiguration.class)
`JpaConfiguration` 클래스의 코드를 확인해 보시면 `@EnableJpaAuditing`이라는 어노테이션을 확인하실 수 있습니다.
해당 어노테이션은 저희가 사용하는 `BaseTimeEntity` 클래스에서 생성 시간과 수정 시간을 자동으로 부여하고, 수정해 주는 역할을 수행합니다.
테스트 클래스 자체는 상관없지만, 해당 테스트의 Fixture 클래스에서는 사용자, 친구 요청과 같이 `BaseTimeEntity`를 상속하고 있는 객체를 생성하는 경우가 존재합니다.
하지만, `BaseTimeEntity`의 경우 `JpaConfiguration`을 통해 `@EnableJpaAuditing`을 가져와야 제대로 수행이 되기에 @Import를 통해 해당 클래스의 빈을 주입받을 수 있도록 했습니다.
해당 클래스를 주입받지 못하면 Fixture에서 save 메서드 수행 시 오류가 발생합니다.

그런데 만약, `JpaConfiguration`은 `@Configuration`의 `@Component`로 자동으로 빈을 생성해 주입할 수 있지 않은가에 대한 질문이라면, `@DataJpaTest`에 대해 알아보아야 합니다.
해당 어노테이션의 경우 Jpa에 필요한 설정들만 등록해 주고, `ComponentScan`을 따로 진행하지 않아 저희가 `@Component`를 통해 등록한 빈들은 가져오지 못합니다.
그래서 직접 `@Import`를 통해 Auditing 설정에 대한 빈을 가져오도록 했습니다.

2023-12-23 06:35 UTC, JJ503 commented on src/test/java/com/backend/blooming/friend/infrastructure/repository/FriendRepositoryTestFixture.java
> +    private EntityManager em;
둘의 용도는 서로 다르게 사용되고 있습니다.

우선 `~RepositoryTestFixture`에서 사용하는 `EntityManager`의 경우 그냥 명시적으로 작성해 줬습니다.
역할 자체만 설명드리자면, `em.flush()`는 DB에 반영하고, `em.clear()`로 영속성 컨텍스트를 지워주었습니다.
그런데 생각해 보니, `@DataJpaTest`에 이미 `@Transactional`이 있고,`save()` 시 자동으로 flush 되기에 굳이 필요는 없을 것 같네요.
굳이 필요하다면, 서비스 테스트 관련 fixture에서 변경 감지를 위해 사용하는 게 더 나을 수도 있겠네요..!
그래서 `~RepositoryTestFixture`에서 `EntityManager`는 제거해 주었습니다.

그리고 `IsolateDatabase`의 경우 테스트 클래스 별 격리를 위해 사용했습니다.
`@DataJpaTest`와는 다르게 `@SpringBootTest`의 경우 `@Transactional`이 존재하지 않아 해당 클래스의 테스트들이 완료되고 이에 대한 데이터가 롤백되지 않습니다.
그렇기에 테스트 격리를 위해선 직접 데이터가 초기화되도록 해주어야 합니다.
이에 대한 것이 `@IsolateDatabase`입니다.

혹시 추가적으로 궁금한 점이 있거나, 설명이 불충분한 부분이 있다면 말씀해주시면 추가적으로 코멘트 남기겠습니다!

2023-12-23 06:37 UTC, JJ503 commented on src/main/java/com/backend/blooming/friend/presentation/FriendController.java
> +            @Authenticated AuthenticatedUser authenticatedUser,
붙일 수 있습니다!
제가 까먹었어요...ㅎㅎ
말씀해주신 부분과 함께 final 누락된 부분들에 대해 추가해주었습니다!

2023-12-23 06:39 UTC, JJ503 commented on src/test/java/com/backend/blooming/friend/presentation/FriendControllerTest.java
> +    MockMvc mockMvc;
MockMvc 외에도 모든 필드들을 이야기하시는 게 맞으시겠죠?
저는 붙여도 상관없습니다.
다만, 지난번에 여쭤봤을 때 붙이질 않길 원하신다고 말씀해 주셔서 붙이지 않았습니다.

지난번과 동일하게 저는 붙여도 괜찮습니다.

2023-12-23 06:40 UTC, JJ503 commented on src/test/java/com/backend/blooming/friend/presentation/FriendControllerTest.java
> +        ).andDo(print()).andDo(
둘을 분리하지 않으면 어떤 형태가 될까요?
질문을 잘 이해하지 못했습니다..!

2023-12-23 06:41 UTC, JJ503 commented on src/test/java/com/backend/blooming/friend/presentation/FriendControllerTest.java
> +                jsonPath("$.message").exists()
jsonPath의 경우 저희가 만들어준 `GlobalExceptionHandler`에서 예외 메시지를 반환하도록 되어있습니다.
선언이란 것이 이런 의미가 맞을까요?

2023-12-23 07:05 UTC, JJ503 commented on src/docs/asciidoc/docs.adoc
> +include::{snippets}/friend-controller-test/친구_요청한다/response-headers.adoc[]
저는 RestDocs를 통해 테스트 빌드로 자동으로 얻을 수 있는 건 snippet으로 알고 있습니다.
snippet도 adoc 파일이라 이 부분에 대한 것과 헷갈리신 건지, 혹은 docs.adoc도 자동으로 생성되는 건지 궁금합니다.
docs.adoc 자동 생성에 대해서는 잘 몰라 이 부분이 맞다면, 공유해 주시면 감사하겠습니다!
snippet의 경우 `build > generated-snippets`에 테스트 클래스 이름의 패키지 내에 메서드 별로 있습니다.

그런데 이와 별개로 찾아보다 보니, docs를 좀 더 깔끔하게 사용할 수 있는 부분에 대해 찾아봤습니다.
아래 내용에 대해 어떻게 생각하시는 지 궁금합니다!

1. 클래스 별로 문서에 대한 adoc 파일을 만들어 편집하고, docs.adoc에서는 해당 파일들을 include 하기만 함
   이를 사용하면 api 문서를 편집할 때 상대적으로 길이가 짧아지니 편하지 않을까 생각합니다.
2. operation을 통해 여러 갱의 snippet을 한 번에 include 하기
   이를 사용하면 아래와 같이 수정될 수 있습니다. (아래 두 가지 방식은 동일한 결과를 반환합니다)
   ```
   // 기존
   include::{snippets}/friend-controller-test/친구_요청을_수락한다/http-request.adoc[]
   include::{snippets}/friend-controller-test/친구_요청을_수락한다/request-headers.adoc[]
   include::{snippets}/friend-controller-test/친구_요청을_수락한다/path-parameters.adoc[]
   
   // 변경 후
   operation::friend-controller-test/친구_요청을_수락한다[snippets='http-request,request-headers,path-parameters']
   ```

2023-12-23 07:09 UTC, JJ503 commented on src/test/java/com/backend/blooming/friend/application/FriendServiceTest.java
> +        );
해당 리뷰는 pr의 중간 커밋에 리뷰가 된 듯 하네요!
현재는 제거된 코드라 다시 확인해주시면 감사하겠습니다.

2023-12-23 07:10 UTC, JJ503 commented on src/test/java/com/backend/blooming/friend/domain/FriendTest.java
> +    static Stream<User> provideUsers() {
바로 위 메서드인 `친구_관계의_사용자_중_한_명인지_확인시_요청자_혹은_요청을_받은_사용자라면_참을_반환한다`를 확인해 보시면 `@MehtodSource`를 확인하실 수 있습니다.
해당 테스트에서 필요한 stream입니다!

2023-12-24 13:19 UTC, JJ503 commented on src/test/java/com/backend/blooming/friend/presentation/FriendControllerTest.java
> +    MockMvc mockMvc;
앗 private 붙이기로 했었군요!
제가 첫 번째 회의 때 기억으로 안 붙이기로 했던걸로 기억했네요..!
private 붙이는 방향으로 수정하도록 하겠습니다.

2023-12-24 13:37 UTC, jhsseonn commented on src/docs/asciidoc/docs.adoc
> +include::{snippets}/friend-controller-test/친구_요청한다/response-headers.adoc[]
docs.adoc 파일 자동 생성 관련해서는 snippet 자동생성과 착각한게 맞습니다.
docs 사용과 관련해서 공유 해주신 방법 중에서는 2번이 조금 더 깔끔하게 docs 파일을 관리할 수 있을 것 같아 2번으로 진행하면 좋을 것 같습니다!
또, 회의 때 논의했던 기능별로 adoc 파일을 다르게 관리하는 방법도 도입해 리팩토링 하면 좋을 것 같습니다.

2023-12-24 13:44 UTC, JJ503 commented on src/test/java/com/backend/blooming/friend/presentation/FriendControllerTest.java
> +        ).andDo(print()).andDo(
회의에서 이야기를 통해 어떤 부분을 궁금해해 주셨는지 이해했습니다.
andDo(print())의 역할은 테스트 수행 시 요청과 응답에 대해 확인하는 것입니다.
저는 테스트가 로직이 제대로 동작하는지 확인하기 위함도 있지만, 코드의 이해를 돕는 역할도 한다고 생각합니다.
그래서 요청과 응답을 콘솔에서 확인한다면, 더 쉽게 해당 테스트와 로직을 이해할 수 있을 것이라 생각해 추가했습니다.
그리고 pr에 말씀드리는 것을 까먹었는데, `~ControllerTest`의 모든 테스트에 `andDo(print())`를 추가했으면 합니다.
해당 부분 의견 주시면 감사하겠습니다!

- andDo(print())가 없는 경우
   ![image](https://github.com/Goal-Tracker/blooming-backend/assets/63184334/0fdabe72-cde1-49bd-bb9a-921109a1f263)

- andDo(print())가 있는 경우
   ![image](https://github.com/Goal-Tracker/blooming-backend/assets/63184334/c3987f94-c799-4052-b661-b0934ea7b31a)

2023-12-29 07:12 UTC, jhsseonn commented on src/test/java/com/backend/blooming/friend/infrastructure/repository/FriendRepositoryTest.java
> +@Import(JpaConfiguration.class)
잘 이해되었습니다! 저의 경우 전자에 대한 질문이었어서 BaseTimeEntity를 사용해 엔티티 공통 속성 공통화 하는 부분에 대해 이해하지 못하고 있었던 것 같습니다. 감사합니다!

2023-12-29 10:10 UTC, jhsseonn commented on src/test/java/com/backend/blooming/friend/presentation/FriendControllerTest.java
> +        ).andDo(print()).andDo(
회의에서 논의했던대로 andDo(print()) 사용해 테스트 결과 볼 수 있게 하면 좋을 것 같습니다!

2023-12-29 11:03 UTC, jhsseonn commented
리뷰 완료했습니다!
다만 질문이 있는데 docs.adoc 파일에서 사용자 관련 api와 테마 색상 api는 따로 adoc 파일로 빼지 않아도 괜찮을까요?
해당 부분을 제외하고는 수정사항 모두 확인 완료했습니다. 수정사항 추가로 보이지 않아서 바로 push 하셔도 괜찮을 것 같습니다.

2023-12-29 14:26 UTC, JJ503 commented
지난 회의 때 말씀드린 바와 같이, 사용자 테마와 부분에 대한 리팩터링은 해당 issue를 만들어 둔 상태이기에 해당 pr에서 진행하도록 하겠습니다.
그래서 이 pr은 여기서 push 하려고 합니다.

2023-12-29 15:01 UTC, jhsseonn commented
앗 확인했습니다! approve 했습니다!

2023-12-29 15:03 UTC, jhsseonn requested changes
approve 하기 전에 발견한 사항 있어서 확인 부탁드립니다!

2023-12-29 15:03 UTC, jhsseonn commented on src/docs/asciidoc/friend.adoc
> +==== 응답
이 부분 원래 응답이 없는 부분일까요? 방금 발견해서 리뷰 남깁니다!

2023-12-29 16:51 UTC, JJ503 commented on src/docs/asciidoc/friend.adoc
> +==== 응답
앗...!
수정 과정에서 누락되었나 보네요.
응답 부분 추가해두었습니다. 확인 감사합니다!

2023-12-30 07:36 UTC, jhsseonn approved these changes
수정 사항 모두 확인했습니다! 바로 push 하셔도 괜찮을 것 같습니다.

2023-12-30 08:12 UTC, merged