골 생성시 골 참여자가 관리자와 친구 상태인지 검증하도록 리팩토링
Goal-Tracker/blooming-backend pull request #35
Opened 2024-01-24 18:08 UTC by jhsseonn

**1/25**
간단한 검증 추가가 주 작업 내용이라 논의할 부분은 없었습니다. 작업내용에 따라서 코드 확인하시고 리뷰 부탁드립니다.

[작업 내용]
- 골 생성시 골 참여 사용자가 친구인지 검증 추가
- 위 검증 추가에 따른 테스트 추가

[컨벤션 수정]
- 유저 검증 메서드명 수정 → `getUser`
- 테스트 코드 비교 검증 수정

2024-01-25 10:02 UTC, JJ503 requested changes
리팩토링 고생 많으셨습니다!
그런데 몇 가지 궁금한 점과 개선하면 좋지 않을까 하는 부분이 있기도 하고,
꼭 수정되어야 하는 로직이 있어 코멘트 및 rc로 일단 처리하도록 하겠습니다..!
해당 부분 확인해 주시면 감사하겠습니다!

2024-01-25 10:59 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        if (!managerId.equals(userId) && !friendRepository.existsByFriendsAndIsFriends(managerId, userId)) {
오 피드백 감사합니다! in절 사용해 조회하는 것으로 변경해보겠습니다.

2024-01-25 11:00 UTC, jhsseonn commented on src/test/java/com/backend/blooming/friend/infrastructure/repository/FriendRepositoryTest.java
> +    void 현재_로그인한_사용자와_입력받은_아이디의_사용자가_서로_친구_관계일_경우_참을_반환한다() {
넵 저도 생각나서 바로 추가했습니다ㅎㅎ 수정해두도록 하겠습니다.

2024-01-27 03:42 UTC, JJ503 commented
갑자기 확인하게 됐는데, closed #${issue}가 아닌 closed issue #${issue}라고 작성해도 PR이 close 될 시 issue도 함께 close 되나요?
![image](https://github.com/Goal-Tracker/blooming-backend/assets/63184334/3b454fa3-a0e7-46cd-853e-96fb9c1f2815)

원래 Development에 issue가 자동으로 설정되어야 하는데, 그러지 않아 여쭤봅니다!
![image](https://github.com/Goal-Tracker/blooming-backend/assets/63184334/33a27763-ffc7-40a0-a19b-98ddb7cefd72)

2024-01-28 08:24 UTC, closed without merging