골 추가 로직 구현 및 테스트
Goal-Tracker/blooming-backend pull request #4
Opened 2023-11-05 13:26 UTC by jhsseonn

**1/21 update**
수정한 내용입니다.

1. 컨벤션 논의사항
    - `deleted` 변수 초기화
    - 골 추가 시 요청에서 `@Valid`로 검증
    - 현재 로그인한 사용자가 참여중인 골 리스트 모두 조회 api 네이밍 수정
2. 기능 관련 논의사항
    - 연관관계 편의 메서드 → `goal` 생성시 `goalTeam` 생성되도록 반영
    - 골 날짜 검증 `GoalTerm`에서 하도록 수정
    - 골 참여자 정보 `fetch join`으로 `goal`에서 바로 조회로 수정
    - `inProgressDays` 삭제
3. 추가한 사항
    - `LocalDate` `@FutureOrPresent` 검증 추가
    - 골에 참여하는 사용자 아이디 리스트 크기가 5가 넘어가면 골 생성 불가 예외처리 추가

---

**1/9 update**
골 추가 부분에 대한 수정 완료 및 골 조회 기능 구현 완료했습니다.
아래는 작업한 내용입니다.

1. 컨벤션 논의사항
    - Value Object 적용 - 골 기간에 대한 정보는 모두 GoalTerm VO로 수정했습니다.
    - DTO 이름 crud 적용
    - 도메인 및 dto 필드 변수명 수정
    - 도메인 필드값 모두 null값 허용하지 않도록 수정 → 빈값이 허용될 경우 빈 문자열 값으로 대체하도록
    
4. 추가한 사항
    - 골 관리자 필드 추가 - managerId
    - 현재 진행중인 골 필드 추가
    - 골 조회 기능
        - 단일 골 조회 - 단일 골에 대한 내용 조회
        - 현재 로그인한 사용자가 참여하는 모든 골 조회

---

**12/9 update**
리뷰에 코멘트 주셨던 수정사항 모두 수정 완료했습니다. 확인 부탁드립니다.
pr #6 머지 이후에 수정해야하는 부분은 아직 수정하지 않았습니다.

---

**11/29 update**
회의에서 이야기했던 컨벤션 최대한 반영했고, 아직 남은 부분은 pr #6 pull 받은 이후 최종 반영하도록 하겠습니다.

**최종 반영한 컨벤션**
1. CustomException으로 예외처리 관리
5. 예외메시지 enum 처리
6. TestFixture 컨벤션 반영

**외에 수정된 부분**
1. 골, 골 팀 도메인에 deleted 필드 추가
3. 골 및 골 팀 생성 로직 수정
4. 골 생성 시 예외처리 domain에서 service로 리팩토링 했고, 그에 따른 예외처리 테스트 또한 모두 GoalServiceTest로 리팩토링 했습니다.
7. GoalRepositoryTest는 service에서 repository를 통해 save하는 부분까지 모두 테스트하고 있어 불필요하다고 생각해 삭제했습니다.

**아직 반영되지 않았고, 추후 반영 예정**
1. 사용자 검색시 존재하는 사용자인지 검증하는 부분 - pr #6 pull 후 리팩토링하면서 반영하겠습니다.
3. BaseTimeEntity 또한 pr #6 pull 후 반영하겠습니다.
4. restDocs 설정 부분 정수님이 작업하신걸로 진행하기로 기억해서 우선 수정은 따로 하지 않았습니다. 마찬가지로 pr #6 pull 후 반영하겠습니다.
5. goalService와 goalController에서 작업중이던 골 삭제 부분 코드가 일부 반영되었는데, 이 부분만 제외하고 커밋을 할 수 없어 어쩔 수 없이 함께 올렸습니다. 해당 코드 제외하고 리뷰 남겨주시면 좋을 것 같습니다!

**함께 이야기 하고 싶은 부분**
1. goalControllerTest에서 goalService에서 골 생성 후 생성된 골 dto를 받아 controller에 응답 dto로 넘겨주는 부분을 given절에서 사용했는데, 해당 부분에서 goalDto가 계속 null로 들어가 테스트를 통과하지 못했습니다... 원인을 계속 찾던 중 작업 기간이 너무 길어져 먼저 pr 올립니다..! 아직 해당 문제 해결하지 못해서 혹시 같은 문제 해결하신 적 있는지 궁금합니다

---

**11/19 update**
- closed #3 
골 추가 컨트롤러 생성 및 골 추가 시 예외처리까지 모두 완료했습니다.
리뷰 부탁드립니다.

**함께 이야기 해보고 싶은 부분**
- ~~goalTeamUserId 리스트 받아올 때 사용자 닉네임으로 받아와 닉네임으로 사용자 id를 검색하는 식으로 구현했습니다. 닉네임 중복 허용하지 않기로 했던 것으로 기억해서 이렇게 했는데 원래 oauthId를 받고자 했는데 oauthId를 사용하는게 더 나을지 궁금합니다. (oauthId도 중복 허용하지 않는 것으로 알고 있습니다.)~~ 
  -> **User id 받아오는 것으로 설정**
- 골 생성에 성공하면 골 생성 후 해당 골 페이지로 넘어가도록 설정해두었는데 이 부분은 안드로이드 분들과 더 이야기 해보는 것이 좋을 것 같습니다. 
  -> **골 생성 후 해당 골 페이지로 넘어가기로 함**
- rest docs를 이번에 처음 사용해봐서 그런데 requestDto에서 goalId를 따로 받지 않았음에도 불구하고 request에서 id가 문서화 되지 않았다고 자꾸 SnippetException이 떠서 id를 문서화하는 코드를 따로 추가해주었더니 오류가 나지 않았습니다.. 비슷한 상황을 겪은 적 있으신지 있다면 어떻게 해결하셨는지 궁금합니다. 
  -> **writeValueAsString에서 설정을 잘못 해줌. 이후 골 삭제, 수정에서 골 id를 받아와야해서 requestDto 수정하기로 함**

---

골 추가 로직 구현 및 테스트 완료했고, 아직 예외처리는 하지 않았습니다.
또, 비즈니스 로직 위주로 작업해 아직 컨트롤러 부분을 작업하지 못했습니다. 추후에 작업해 올리도록 하겠습니다.

**작업내용**
- 최대한 TDD 방식으로 프로그래밍 하려 노력했습니다.
- 골 생성에 필요한 `CreateGoalDto`를 만들어 입력받고, 해당 dto의 입력받은 내용으로 최종적으로 엔티티를 생성하도록 했습니다.
- 골 시작일과 종료일을 `String` 형태로 받아 `Date` 형식으로 바꾸는 함수를 따로 구현했습니다. 해당 부분 아예 도메인 생성할 때 `DateTime` 형식 쓰는 것이 더 좋겠다 판단되시면 수정하도록 하겠습니다.

이상 오늘까지 작업한 내용 우선 pr 요청합니다.

2023-11-19 13:11 UTC, JJ503 commented
> goalTeamUserId 리스트 받아올 때 사용자 닉네임으로 받아와 닉네임으로 사용자 id를 검색하는 식으로 구현했습니다. 닉네임 중복 허용하지 않기로 했던 것으로 기억해서 이렇게 했는데 원래 oauthId를 받고자 했는데 oauthId를 사용하는 게 더 나을지 궁금합니다. (oauthId도 중복 허용하지 않는 것으로 알고 있습니다.)

식별자인 ID를 두고 굳이 다른 필드를 통해 조회해 올 필요는 없다고 생각합니다.
현재 제 쪽의 구현이라 반영이 안 되어 있지만, `@Authenticated` 통해 이 문제는 해결할 수 있을 것 같네요!

> 골 생성에 성공하면 골 생성 후 해당 골 페이지로 넘어가도록 설정해 두었는데 이 부분은 안드로이드 분들과 더 이야기해 보는 것이 좋을 것 같습니다.
오늘 회의에서 이야기했기에 넘어갑니다.
회의 결과 : 골 페이지로 넘어가기

> rest docs를 이번에 처음 사용해 봐서 그런데 requestDto에서 goalId를 따로 받지 않았음에도 불구하고 request에서 id가 문서화되지 않았다고 자꾸 SnippetException이 떠서 id를 문서화하는 코드를 따로 추가해 주었더니 오류가 나지 않았습니다.. 비슷한 상황을 겪은 적 있으신지 있다면 어떻게 해결하셨는지 궁금합니다.
요청 시 request가 아닌 response를 전달하고 있어서 그런 것으로 보입니다..!

---
오늘 회의를 바탕으로 각자 다시 수정하고 리뷰 요청하기로 했기 때문에, 따로 리뷰는 진행하지 않고 코멘트만 남겨둡니다.
완료 후 다시 리뷰 요청 주세요!

2023-12-02 05:11 UTC, JJ503 requested changes
전체적으로 final, 개행, 정렬, 띄어쓰기가 잘 안 되어 있는 부분들이 많았습니다. 확인 부탁드립니다.
질문과 수정되었으면 하는 사항들에 대해 작성해보았는데, 확인 부탁드립니다.

2023-12-02 05:16 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    public boolean isGoalAvailable(String goalStartDay, String goalEndDay) throws ParseException {
객체지향적인 측면에서 이 골이 유효한가?라는 상태를 알려주는 것은 goal 자신이 직접 해야 할 일이라고 생각했습니다.
이와 상관없더라도 서비스에 있게 된다면, getter가 너무 남발되기도 하고 추후 동일한 메서드가 필요할 때마다 만들어 사용해야 한다는 문제점도 있을 것이라 생각합니다. 이때, 해당 메서드는 매번 달라지는 것이 아닌 정책과 같은 사항이기에 더더욱 도메인에 있어야 한다고 생각합니다.

2023-12-02 05:19 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/application/fixture/GoalServiceFixture.java
> +@SpringBootTest
없어도 가능하다는 이야기를 회의를 통해 말씀드렸으며, 제거한 것도 확인했습니다.

2023-12-02 05:20 UTC, JJ503 requested changes
별관련 리뷰 추가합니다

2023-12-02 05:20 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/presentation/GoalControllerTest.java
> +import static org.springframework.restdocs.payload.PayloadDocumentation.*;
별이 보이네요!

2023-12-02 05:21 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    public Goal(
혹시 논의가 되었을까요?

2023-12-02 05:22 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    public Goal(
논의 결과가 어떻게 되었을까요?

2023-12-02 05:23 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/infrastructure/repository/GoalRepositoryTest.java
> +class GoalRepositoryTest {
save만 이라기보다는, 저희가 만든 메서드가 아닌 기본적으로 주어지는 메서드에 대해서도 테스트를 해야 할까에 대한 질문이긴 했습니다.
save() 메서드에 대해 저희가 구현을 한 것도 아닌데 굳이 해야 할 필요가 있을까요?

2023-12-02 05:26 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
> +}
기존에 37번 라인 이후에 개행이 존재하지 않았습니다. 그래서 아래 이미지와 같이 뜬 것을 보셨을 수도 있습니다.
![image](https://github.com/Goal-Tracker/blooming-backend/assets/63184334/9ed2f55e-09ac-4906-992e-4de2290b0ce6)

그런데 컨벤션상 클래스의 코드가 종료된 후에는 개행을 항상 추가해주어야 합니다. ([해야 하는 이유](https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/))
이번 pr 요청 시에는 제가 전달드린 설정이 완료되었기 때문인지 개행이 잘 들어가 있습니다!

2023-12-06 08:10 UTC, jhsseonn commented on src/test/java/com/backend/blooming/goal/infrastructure/repository/GoalRepositoryTest.java
> +class GoalRepositoryTest extends GoalServiceFixture {
현 pr 시점에서는 골 추가 기능만 존재했었기에 당장은 GoalRepository에서 테스트 할 메서드가 없다고 판단하여 GoalRepositoryTest는 삭제처리했습니다. 삭제한 부분이 커밋에 반영되지 않은 것으로 보여 다시 커밋했습니다.

2023-12-06 08:15 UTC, jhsseonn commented on src/test/java/com/backend/blooming/goal/infrastructure/repository/GoalRepositoryTest.java
> +                .build();
위에서 말씀드린 것처럼 현 pr 시점에서는 꼭 테스트가 필요하지 않다고 판단해 해당 테스트는 삭제했으나 커밋이 반영되지 않아 다시 커밋 올렸습니다. 삭제 전에 해당 부분에서 오류가 따로 나진 않았었는데 추후에 repostiroy 테스트 수행하면서 보도록 하겠습니다!

2023-12-06 08:16 UTC, jhsseonn commented on src/test/java/com/backend/blooming/goal/application/GoalServiceFixture.java
> +public class GoalServiceFixture extends DateFormat {
네! 우선 GoalServiceTestFixture로 리네이밍 해두었습니다!

2023-12-08 13:25 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +    public ResponseEntity<GoalResponse> createGoal(@RequestPart @Valid GoalRequest request) throws ParseException {
RequestBody를 생각하지 못하고 RequestPart를 사용했는데 해당 부분 때문에 컨트롤러 테스트에서 오류가 나고 있던 것 같습니다.. RequestBody로 설정해주니 테스트 성공적으로 잘 돌아갔습니다!

2023-12-08 13:26 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        return ResponseEntity.created(URI.create("/goals/" +goalResponse.goalId())).body(goalResponse);
redirect url을 전달하면서 해당 uri에서 전달해주어야할 정보들을 body로 넘기고자 함이었는데 조회 부분은 따로 api를 만드는 편이 좋을까요?

2023-12-08 13:28 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        return ResponseEntity.ok("삭제 완료되었습니다.");
백쪽에서 굳이 문구를 반환해줄 필요는 없겠군요! 수정하겠습니다.

2023-12-08 13:29 UTC, jhsseonn commented on build.gradle
> +	id 'java-test-fixtures'
fixture 사용법을 찾아보면서 해당 플러그를 추가해서 추가해주었는데 불필요한 플러그일 경우 삭제하도록 하겠습니다.

2023-12-08 13:30 UTC, jhsseonn commented on build.gradle
> +	testAnnotationProcessor 'org.projectlombok:lombok:1.18.24'
위 이유와 동일합니다.

2023-12-08 13:33 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    public Goal persistGoal(CreateGoalDto createGoalDto) {
넵 수정하도록 하겠습니다.

2023-12-08 15:15 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +//        }
넵 다음엔 유의하도록 하겠습니다.

2023-12-08 15:24 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +@Table(name = "goal")
저는 db에 저장될 때 table명을 설정해주기 위해 했었는데 굳이 이 과정을 거치지 않아도 알아서 테이블명이 설정되는걸까요?

2023-12-08 15:25 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    private Long id;
이건 GoalTeam과의 연관관계매핑 과정에서 Goal id를 찾기 위해 설정해주었습니다. 꼭 필요하지 않은 과정인지 더 찾아보도록 하겠습니다!

2023-12-08 15:27 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    private boolean deleted;
이 부분 빠졌었네요..! 설정해주었습니다!

2023-12-08 15:29 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    }
확실히 지금은 true가 false가 되는 경우는 없겠네요! 지금은 바로 deleted를 true로 바꿔주어도 괜찮을 것 같습니다

2023-12-08 17:03 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +        return true;
좋은 것 같습니다! 다만 골 추가 과정에서는 당장은 필요하지 않은 기능이라 판단해 해당 메서드는 이번 pr에서는 삭제하였습니다. 추후 골 수정 및 삭제 기능 구현에서 해당 메서드 다시 반영하도록 하겠습니다.

2023-12-09 07:38 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    }
해당 부분 domain에 있는 건 부적절해보여서 goalDto 쪽에서 goal 받아서 해당 goal의 goalTeam 목록 모두 가져와 아이디만 따로 리스트로 저장하는 식으로 변경했습니다.

2023-12-09 07:38 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    public boolean isGoalAvailable() {
넵 해당 메서드는 삭제 및 수정 때 다시 작성하도록 하겠습니다.

2023-12-09 07:40 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
> +    }
컨벤션 적용해 생성자 함수로 바꿔주었습니다.

2023-12-10 04:34 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/application/GoalServiceFixture.java
> +    protected String 사용자_oauth_아이디 = "아이디";
수정되기 전에는 지역 변수로 선언되어 있기 때문에 의문이 들었습니다. 그리고 전역 변수는 아니길 바랐고요!

수정된 후에는 oauthId가 "아이디"라는 문자열로 들어갈 일이 없기도 하고, 해당 경우 빌더 패턴을 사용했기에 oauthId임이 바로 보여 굳이스럽다는 생각을 했습니다.
해당 부분은 아이디뿐만 아니라 이메일과 이름에 대해서도 동일하게 생각했습니다.
하지만, 우선 제가 꼭 수정하길 바라는 부분은 수정이 완료되었기에 위 내용에 대해선 효선님 판단에 맡기도록 하겠습니다.

2023-12-10 04:35 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/dto/response/GoalResponse.java
> +        @JsonProperty("goalId")
변수와 이름이 다를 때는 꼭 필요하지만, 동일할 때는 불필요합니다!

2023-12-10 04:41 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +    public ResponseEntity<GoalResponse> createGoal(@RequestPart @Valid GoalRequest request) throws ParseException {
RequestPart의 경우 MultiPart로 값을 전달해줘야 하기 떄문에 오류가 발생한 것으로 보이네요!

2023-12-10 04:46 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        return ResponseEntity.created(URI.create("/goals/" +goalResponse.goalId())).body(goalResponse);
이 부분은 안드로이드 측과 협의가 필요할 것으로 보이지만 개인적인 생각만 작성해 보도록 하겠습니다!

생성과 동시에 값을 바로 받아서 처리해야 할 일이 있는 것이 아니라면 저는 불필요하다고 생각합니다.
특히, Location을 통해 바로 리다이렉트 url을 넘긴다는 의미는 생성되었을 때 바로 해당 url로 요청해라 라는 의미로 보입니다.
리다이렉트 하기 전에 안드로이드 측에서 처리해야 할 데이터가 아니라면 저는 응답 값으로 생성된 골 id를 조회하는 location만 전달되어도 충분하다고 생각합니다.

그리고 조회 API는 꼭 필요하다고 생각합니다.
만약 해당 API가 존재하지 않는다면, 현재 location으로 설정한 url은 오류가 존재하지 않는 url로 처리되게 될 것입니다.
또한, 생성 시 외에는 아예 조회를 할 수 없는 상황이 되기에 조회 API는 꼭 필요하다고 생각합니다.

2023-12-10 04:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +@Table(name = "goal")
네 맞습니다.
설정해주지 않는다면 그냥 도메인으로 설정한 `goal`이라는 이름의 테이블이 생성되게 됩니다.
그래서 저 역시 다로 설정해 주지 않았습니다.

설정해 준 곳은 `user`였는데, 이유는 다음과 같습니다.
도메인 명으로는 `users`보다는 `user`가 적절하다고 생각했습니다.
하지만, `user`는 mysql의 예약어로 테이블 명으로 사용하기에 적절하지 않다고 판단했습니다.
그래서 도메인 명은 `user`, 테이블 명은 `users`로 사용하기 위해 설정해 주었습니다.

2023-12-10 04:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    private Long id;
칼럼 명이 될 텐데 그냥 id 여도 충분하지 않은가 생각합니다.
이미 테이블에서 goal임을 알 수 있기 때문에요!

2023-12-10 05:00 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
> +    private Goal goal;
앗 아이디가 아닌 forignKey에 대한 이야기였습니다! 아래와 같은 옵션입니다.
`foreignKey = @ForeignKey(name = "")`

해당 옵션은 foreignKey로 설정하겠다는 제약 조건의 이름을 변경할 수 있는 옵션입니다.
만약 설정하지 않는다면 아래 이미지와 같이 

설정한다면, 아래와 같이 저희가 알아볼 수 있는 이름으로 설정할 수 있습니다.

2023-12-10 05:10 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
> +        result.updateGoalTeams(goalTeamsResult);
수정된 내용 확인했습니다.
그런데 개인적으로 `골을 생성한다`라는 테스트와 `골 팀을 생성한다`라는 테스트는 합쳐지는 것이 적절하다고 생각합니다.
그리고 `createGoalTeams`는 private으로 선언되는 것이 적절하다고 생각하고요.
해당 메서드뿐만 아니라 해당 클래스에 있는 메서드들 중 `createGoal`를 제외하고는 모두 private으로 선언되어야 한다고 생각하는데, 어떻게 생각하시는 지 궁금합니다!

2023-12-15 15:57 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
> +    private Goal goal;
아하 그럼 이렇게 foreign key 이름 설정해주겠습니다!
혹시 foreign key 이름 양식도 통일하는 것이 좋을까요?
ex) fk_user_id 이런 식으로요!

2023-12-15 16:12 UTC, jhsseonn commented on src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
> +        result.updateGoalTeams(goalTeamsResult);
골 생성 이후에 따로 골 팀을 생성해야하는 경우가 있을거라 생각해 public으로 설정했는데 지금 당장 public으로 설정해야하는 것은 아닌 것 같아 private으로 설정해두겠습니다.
테스트의 경우 골 생성 시 골 팀 생성까지 하기 때문에 지금 꼭 필요한 테스트로 보이지는 않습니다. 이 부분도 둘이 같이 합쳐두는 것으로 수정하겠습니다.

그리고 위에 언급한 골 생성 이후 따로 골 팀을 생성하는 하는 것에 예시를 들자면 
만약 `골을 생성한 후에 참여 사용자를 따로 초대할 경우`가 있을 것 같습니다. 이 경우, 골 수정에 해당하는 것 같아 골 수정 구현하면서 필요하다면 다시 public으로 수정하도록 하겠습니다!

2024-01-11 04:03 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
> +    private Goal goal;
id까지는 불필요하다고 생각해서, fk를 만드는 `fk_{fk를 만드는 도메인 이름}_{fk로 만드는 필드명}`로 하면 어떨까 싶습니다!

2024-01-11 04:13 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
> +        result.updateGoalTeams(goalTeamsResult);
골 생성 이후 팀을 생성해야 하는 경우 자체가 잘 이해가 되지 않습니다.
팀 생성 후 사용자를 초대하는 경우 팀을 생성하는 것이 아닌, 팀에 사용자를 추가하는 것이므로, 다른 기능이라고 생각합니다.
그래서 팀을 생성하는 메서드 자체는 private이 적절하다고 생각합니다.

추가적으로, 팀을 생성하는 것을 `service` 클래스가 아닌 `goal`에서 진행해 보는 것은 어떨까요?
`goalTeam`의 경우 `goal`이 생성될 때 무조건 만들어져야 하기 때문입니다.
`연관관계 편의 메서드`에 대해 검색해 보시면 좋을 것 같습니다!

2024-01-11 04:18 UTC, JJ503 commented
별건 아니지만, 기본 merge 메시지가 아닌 두 번째 이미지와 같이 커밋을 진행하기로 했던 것으로 기억합니다.
그냥 리마인드차 말씀드립니다!
방법은 이전에 전달드린 노션을 통해 확인하실 수 있습니다.

<img width="591" alt="image" src="https://github.com/Goal-Tracker/blooming-backend/assets/63184334/c366d865-83ca-46ff-82fd-da627f6c1ecb">
<img width="715" alt="image" src="https://github.com/Goal-Tracker/blooming-backend/assets/63184334/1c6d20cb-885e-4e82-8b65-9f5f7954d951">

2024-01-11 07:03 UTC, JJ503 requested changes
추가적인 기능들이 있었는데, 구현하시느라 고생 많으셨습니다.
하지만, 아직 몇 가지 의견을 나누고 싶은 부분들이 있기도 하고 수정해야 할 부분들이 보여 rc로 두었습니다.
확인해 주시면 감사하겠습니다!
그리고, 이전 리뷰들에서도 코멘트 남긴 부분들에 대해 답변 남겨둔 부분들이 있어 해당 부분들 확인해주시면 감사하겠습니다!

그리고 push 후 sonarcloud의 issue를 확인해보시면 좋을 것 같아요!

2024-01-11 07:03 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
> +import com.fasterxml.jackson.annotation.JsonIgnore;
사용하지 않는 import 문이 있습니다.
이와 비슷한 곳들이 몇 곳 있어 sonarcloud에서 issue 확인해 주시길 바랍니다.

2024-01-12 12:24 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/response/GoalResponse.java
> +        @JsonProperty("goalId")
JsonProperty로 설정하지 않고 바로 Request/Response dto 변수를 가져다 쓰도록 수정 완료했습니다.

2024-01-12 12:25 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/request/GoalRequest.java
> +        @JsonProperty("goalId")
위에 말씀드린대로 json과의 파싱을 위해 설정해주었으나 바로 dto 변수로 파싱하도록 수정하였습니다.

2024-01-12 12:27 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        return ResponseEntity.created(URI.create("/goals/" +goalResponse.goalId())).body(goalResponse);
단일 골에 대한 조회 기능과 현재 로그인한 사용자가 참여한 골 목록 조회 기능을 따로 추가하였습니다. 조회 기능 관련해서 더 논의하고 싶은 내용이 있는데 아래 조회 기능에서 더 자세히 적어두도록 하겠습니다.

2024-01-12 12:28 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +public class GoalService extends DateFormat {
날짜 데이터 모두 LocalDate로 수정하고 날짜 관련된 필드는 모두 GoalTerm VO로 처리하였습니다.

2024-01-12 12:29 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    private Long id;
해당 부분 수정 완료했습니다.

2024-01-12 12:33 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    private boolean deleted;
변수 초기화의 경우 일관성을 주고 싶어 빌더에서 설정해주었습니다. 이 부분은 서로 맞춰서 통일하는게 어떨까요?

2024-01-12 12:33 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +            log.info("이미 종료된 골입니다.");
해당 로그는 미처 삭제하지 못하고 커밋으로 올라간 것으로 보입니다..! 삭제하도록 하겠습니다.

2024-01-12 12:34 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
> +@Table(name = "goalTeam")
해당 부분 수정 완료했습니다.

2024-01-12 12:34 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
> +    @Column(name = "goal_team_id")
해당 부분 수정 완료했습니다.

2024-01-12 12:35 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
> +    private Goal goal;
해당 부분 이야기 했던 것을 미처 생각하지 못했습니다..! 이번 수정 때 수정해서 다시 업로드 하도록 하겠습니다!

2024-01-12 12:36 UTC, jhsseonn commented on src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
> +        result.updateGoalTeams(goalTeamsResult);
넵 방법 다시 고려해보도록 하겠습니다!

2024-01-12 12:40 UTC, jhsseonn commented on build.gradle
> +	testImplementation 'org.mockito:mockito-inline:3.6.0'
확인해보니 사용하는 곳이 없어 삭제했습니다!

2024-01-12 12:40 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    }
넵 연관관계 편의 메서드에 대해 공부해보겠습니다!

2024-01-12 12:43 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        validateGoalDatePeriod(createGoalDto.startDate(), createGoalDto.endDate());
해당 검증은 빌더로 넘어가기 전 입력받은 값들에 대한 검증이 필요하다고 생각해 서비스에서 검증을 한차례 진행했는데 GoalTerm을 생성하면서 GoalTerm에서도 비슷하게 검증을 거치고 있어 GoalTerm에서 모든 검증을 처리해주어도 좋을 것 같습니다!
그리고 요청 받을 때 @Valid 어노테이션으로 한차례 검증을 거치는 것을 잊고 있었습니다..!!! 해당 부분은 다시 추가하도록 하겠습니다!

2024-01-12 12:45 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    }
골에 참여자로 추가할 수 있는 사용자가 현재 친구 관계인 사용자만 해당한다는 것을 미처 생각하지 못했던 것 같습니다..! 골 추가/조회도 이미 너무 늦어져서 이 부분은 따로 이슈를 만들어서 진행하는 것이 좋을 것 같습니다!

2024-01-12 12:48 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        final List<GoalTeamWithUserNameDto> goalTeamWithUserQueryProjectionDtos = goalTeamWithUserNameRepository.findAllByGoalIdAndDeletedIsFalse(goal.getId());
해당 부분은 toMany 관계의 fetch join시 쿼리 조회가 N+1만큼 되는 문제를 개선하고자 Goal 엔티티에서 toMany 관계인 goalTeam을 따로 불러오려고 했습니다. 그런데 착오가 있어 현재 N+1 문제가 해결되지 않아 N+1 문제가 해결되도록 코드를 수정하고자 합니다!

2024-01-12 16:37 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        });
위와 동일하게 N+1 문제를 개선하고자 goalTeam을 따로 불러오게 되었습니다. 
지금 생각한 개선법으로는 GoalTeamWithUserNameDto를 repository에서 검색할 때 where 조건절에서 in 절로 해당 리스트에 저장되어 있는 모든 골 아이디의 정보를 한번에 갖고 올 수 있도록 goalIdsUserAttend 리스트 자체를 파라미터로 넘겨주려 합니다. 이렇게 되면 단일 골 조회에서는 같은 메서드를 사용하기 보단 정수님이 말씀하신대로 goal에서 fetch join으로 한번에 모든 정보를 불러온 다음 필요한 정보들만 dto로 정리해서 넘겨주는 식으로 구현하는 것이 좋을 것 같습니다. 지금 생각한 방법으로는 이렇게 진행해보려 합니다!

2024-01-12 16:45 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTerm.java
> +    private long getValidGoalDays(final LocalDate startDate, final LocalDate endDate) {
days는 전체 골 날짜수이고 inProgressDays는 현재 진행중인 날짜입니다. 그러니까 총 30일 중 오늘이 10일 째라면 days는 30, inProgressDays는 10일이 됩니다. 쓰다보니 inProgressDays는 매번 조회할 때마다 갱신을 해주어야겠네요... 이 부분 빠진 것 같아 따로 추가하도록 하겠습니다! 
그리고 말씀하신대로 목적 파악이 어려울 수 있을 것 같아 해당 필드 및 메소드는 이름을 알기 쉽게 바꾸는 것도 고려해보겠습니다! 
그리고 기존 api 상으로는 goalDays를 받는데 애초에 날짜수가 시작날짜와 종료날짜로 계산한 값이라 서버쪽에서 계산해서 값을 넣어주는 것이 맞겠다는 생각이 들어 시작날짜와 종료날짜만 받아 값을 계산하는 로직으로 변경했습니다. 그래서 api가 추가 부분이 조금 수정되었는데 이건 제가 정수님께 피드백 부탁드린다는 것을 깜빡했습니다...! api 명세서 변경된 부분 노션에 올려두도록 하겠습니다!

2024-01-12 16:47 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/infrastructure/repository/GoalTeamRepository.java
> +public interface GoalTeamRepository extends JpaRepository<GoalTeam, Long> {
골에서 toMany 관계에 있는 골 팀은 따로 가져오는 것으로 고려하다보니 GoalTeamRepository를 따로 생성하게 되었습니다! 기능적으로는 골 팀만 가져오는 경우는 없습니다.

2024-01-12 16:51 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +        this.memo = setNewMemo(memo);
값을 넣어준다는 의미에서 input을 사용해도 좋을 것 같습니다. process가 저는 잘 와닿지 않는 느낌이어서 의견 드립니다!

2024-01-12 16:51 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
> +    @JoinColumn(name = "user_id", foreignKey = @ForeignKey(name = "fk_user_id"), nullable = false)
넵 수정하도록 하겠습니다!

2024-01-12 16:52 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +    @PostMapping(value = "/add", headers = "X-API-VERSION=1")
오 이 부분은 전혀 이렇게 생각하지 못했던 것 같아요..!!! 듣고보니 http method만으로도 충분히 의미 전달 되는 것 같아서 변경 고려해보겠습니다!

2024-01-12 16:55 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +    @GetMapping(value = "/main", headers = "X-API-VERSION=1")
현재 로그인한 사용자가 참여한 골을 모두 조회하는 것은 메인 화면에서 필요한 기능어서 main으로 기재해두었습니다. 이 부분이 사실 딱 맞는 네이밍이 생각나지 않아서 임시방편으로 main으로 적어두었는데 확실히 기능의 의미가 와닿게 변경하는 편이 좋을 것 같아 네이밍 고려해보도록 하겠습니다!

2024-01-12 16:55 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        final ReadAllGoalResponse readAllGoalResponse = new ReadAllGoalResponse(readAllGoalDtos);
필요한 파라미터가 하나뿐이라 from 사용하지 않고 바로 생성자를 사용했습니다. 통일하는 편이 좋을까요?

2024-01-12 16:56 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/request/CreateGoalRequest.java
> +        LocalDate endDate,
몰랐던 부분이라 미처 생각하지 못했네요..!! 고려해보도록 하겠습니다!

2024-01-12 16:56 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/request/CreateGoalRequest.java
> +public record CreateGoalRequest(
네.. 누락입니다... 변경된 부분 모두 회의록에 올려두겠습니다!

2024-01-12 17:00 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/response/ReadAllGoalResponse.java
> +        List<ReadAllGoalDto> readAllGoals
이 부분은 ReadAllGoalDto들을 가지고 와 ReadAllGoalResponse dto로 한번 감싸서 json으로 보내는 것이라 ReadAllGoalDto가 맞습니다! 그래서 필드명을 골을 조회한다는 의미로 readAllGoals로 설정하였습니다.

2024-01-12 17:01 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/response/ReadGoalResponse.java
> +public record ReadGoalResponse(
네 맞습니다! 그래서 api를 수정했는데 수정본 전달을 깜빡했습니다.. 회의록에 올려두도록 하겠습니다!

2024-01-12 17:03 UTC, jhsseonn commented on src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
> +        assertSoftly(softAssertions -> {
맞아요 모든 정보를 비교 검증하려 하니 테스트 코드가 쓸데없이 너무 길어지더라구요.. 말씀하신대로 값 비교 검증은 정보 하나에 대해서만 진행하고 나머지는 id만 비교하는 식으로 하면 어떨까요?

2024-01-12 17:06 UTC, jhsseonn commented on src/test/java/com/backend/blooming/goal/presentation/GoalControllerTest.java
> +                .header("X-API-VERSION", "1")
엇 정수형이 맞는 것 같습니다..! 수정하도록 하겠습니다!

2024-01-13 04:40 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTerm.java
> +        long inProgressDays = ChronoUnit.DAYS.between(startDate, nowDate) + 1;
해당 변수는 이후 수정이 가능해야해서 final 붙이지 않았습니다!

2024-01-13 11:07 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    private boolean deleted;
통일하면 좋을 것 같습니다!
저는 개인적으로 해당 변수를 파라미터로 받지도 않기 때문에, 굳이 빌더에서 초기화해 줄 필요가 없다고 판단해 필드에서 바로 초기화를 진행해 주었습니다.
필드를 보았을 때 초기화되어 있지 않다면, 대충 봤을 때 빌더를 통해 초기화해줘야 한다고 생각할 수도 있을 것 같아서 해당 방식을 택했습니다.
하지만, 두 사람의 방식이 동일하다면 헷갈릴 걱정은 좀 줄어들 것 같긴 하네요.
제 방식에 대해서도 의견 주시면 감사하겠습니다!
내일(1/14) 회의에서 한 가지 방식을 채택하면 좋겠네요.

2024-01-13 11:10 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    }
저도 동일하게 당장은 그냥 사용자로 진행해도 충분할 것 같네요!
아무래도 제가 친구 파트를 늦게 시작하게 되어 영향을 드리게 된 것 같아 죄송하네요 🥲

2024-01-13 11:17 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        final List<GoalTeamWithUserNameDto> goalTeamWithUserQueryProjectionDtos = goalTeamWithUserNameRepository.findAllByGoalIdAndDeletedIsFalse(goal.getId());
제가 jpa에서 fetch join을 사용하면 n+1 문제가 발생하지 않는다고 알고 있습니다.
오히려 하나의 쿼리만 발생할 수 있게 도와줍니다.
oneToMany 관계의 데이터를 한 개까지는 fetch join을 통해 가져오더라도 distinct를 통해 중복되는 값도 제거해 준다고 알고 있습니다.
혹시 제가 잘못 알고 있는 걸까요?
fetch join을 사용해 어떤 로직을 구현하셨을 때 n+1 문제가 발생했는지 궁금합니다!

2024-01-13 11:18 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        });
위 코멘트와 동일하게 어떤 쿼리를 사용했을 때 n+1 문제가 발생했는지 궁금합니다.

2024-01-13 11:24 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/GoalTerm.java
> +    private long getValidGoalDays(final LocalDate startDate, final LocalDate endDate) {
inProgressDays를 저장해야 하는 이유가 있을까요?
매일마다 모든 goal의 inProgressDays를 업데이트해 주는 것이 더 불편할 것 같네요.
어차피 조회 때마다 갱신할 것이라면, 저장하지 않고 계산해 준 값을 반환해 주는 것이 적절할 것 같다는 생각이 들어요.
혹은 그 정도는 안드로이드 측에서 진행해도 충분할 것 같기도 하고요! -> 개인적으로는 이게 더 나을 것 같아요.
일단 저장자첸느 불필요하다고 생각합니다.

2024-01-13 11:25 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +        this.memo = setNewMemo(memo);
개인적으로 input이 더 와닿지 않네요...
좀 더 적절한 네이밍을 찾아야 할 것 같아요.

2024-01-13 11:31 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +    @GetMapping(value = "/main", headers = "X-API-VERSION=1")
만약 모든 goal을 조회해 올 것이라면, 제 경우 `all`을 사용했는데 어떠신가요?
모든 사용자 목록 조회 시에 사용했습니다.

2024-01-13 11:35 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        final ReadAllGoalResponse readAllGoalResponse = new ReadAllGoalResponse(readAllGoalDtos);
다른 `from` 메서드들도 동일하지 않나요?
정적팩토리 메서드에서 `from`은 파라미터가 하나일 때 사용합니다!

사실 파라미터보다는, 정적팩토리 메서드를 사용하게 된 계기가 파라미터로 바로 생성하는 것이 아니라, 파라미터를 사용해 해당 객체를 생성하기 때문에 사용하게 되었다고 생각합니다.
`ReadAllGoalResponse`에서 현재 dto를 바로 필드로 넣어서 이해가 되지 않는 것은 아니지만, 필드 자체가 저는 잘못되었다고 생각해 해당 수정과 함께 수정되었으면 합니다.
그리고 통일성의 문제도 있고요!

2024-01-13 11:43 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/dto/response/ReadAllGoalResponse.java
> +        List<ReadAllGoalDto> readAllGoals
저는 `response`에서 `ReadAllGoalDto`를 필드로 갖고 있는 것 자체가 적절하지 않다고 생각합니다.
해당 방식으로 진행한다는 의미는 `service`에서 view에 대해 알고 있어 view에서 원하는 값을 전달해 준다는 것으로 보입니다.
하지만, view에서 원하는 값으로 변환해줘야 하는 것은 `controller`의 역할이라고 생각합니다.
또한, `service`에서는 `infrastructure`를 통해 가져온 값을 전달하는 그 이상 그 이하도 아니라고 생각합니다.
그렇지 않다면, 만약 `view`에서 전달받아야 하는 값이 변경되게 된다면 두 레이어에 있는 dto가 모두 수정되게 될 수도 있기 때문입니다.
그래서 가능하면, `service`의 dto는 `repository`를 통해 가져온 정보를 그대로 전달하고, 가져온 값들 중 api response에 맞추는 것은 `controller`의 dto가 할 일이라고 생각했습니다.

그렇기 때문에 `ReadGoalResponse`와 `ReadGoalDetailDto`에서 다른 필드는 날짜가 문자열로 바뀐 것 밖에 없는데, `service` 레이어의 dto에서 문자열로 바꾸지 않고 `controller`의 dto에서 변경해 반환했다고 생각합니다.

2024-01-13 11:44 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
> +        assertSoftly(softAssertions -> {
그렇다면, 이번 pr에서 해당 작업 진행해 주시면 감사하겠습니다!
저는 현재 진행 중인 이슈 완료 후, 통일성을 위해 리팩터링 작업을 진행하는 것으로 하겠습니다.

2024-01-13 11:57 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        final List<GoalTeamWithUserNameDto> goalTeamWithUserQueryProjectionDtos = goalTeamWithUserNameRepository.findAllByGoalIdAndDeletedIsFalse(goal.getId());
방금 아래와 같은 쿼리로 테스트를 진행해 본 결과 n+1문제는 발생하지 않았습니다.

``` java
 @Query("""
      SELECT g
      FROM Goal g
      JOIN FETCH g.teams t
      JOIN FETCH t.user u
      WHERE u.id = :userId
  """)
  List<Goal> findAllByUserId(final Long userId);
```

```
Hibernate: 
    /* SELECT
        g 
    FROM
        Goal g 
    JOIN
        FETCH g.teams t 
    JOIN
        FETCH t.user u 
    WHERE
        u.id = :userId */ select
            g1_0.id,
            g1_0.memo_default,
            g1_0.created_date_time,
            g1_0.deleted,
            g1_0.days,
            g1_0.end_date,
            g1_0.in_progress_days,
            g1_0.start_date,
            g1_0.last_modified_date_time,
            g1_0.manager_id,
            g1_0.memo,
            g1_0.name,
            t1_0.goal_id,
            t1_0.id,
            t1_0.created_date_time,
            t1_0.deleted,
            t1_0.last_modified_date_time,
            t1_0.user_id,
            u1_0.id,
            u1_0.theme_color,
            u1_0.created_date_time,
            u1_0.is_deleted,
            u1_0.email,
            u1_0.last_modified_date_time,
            u1_0.name,
            u1_0.oauth_id,
            u1_0.oauth_type,
            u1_0.status_message 
        from
            goal g1_0 
        join
            goal_team t1_0 
                on g1_0.id=t1_0.goal_id 
        join
            users u1_0 
                on u1_0.id=t1_0.user_id 
        where
            t1_0.user_id=?
```

### 결과
```
[Goal(MEMO_DEFAULT=, id=1, name=골 제목, memo=골 메모, goalTerm=com.backend.blooming.goal.domain.GoalTerm@400fae9b, managerId=1, deleted=false), 
Goal(MEMO_DEFAULT=, id=2, name=골 제목2, memo=골 메모2, goalTerm=com.backend.blooming.goal.domain.GoalTerm@e8e5cfe, managerId=1, deleted=false)]
```

2024-01-13 12:03 UTC, JJ503 requested changes
아직 리뷰 반영이 일어나지 않았지만, 도움이 될까 싶어 추가적인 코멘트 남겨두었습니다.
그리고 추가 리뷰로는 `fixture` 변수 설정 시 더 좋지 않을까? 하는 사항에 대해 작성해 보았습니다.

2024-01-13 12:03 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/infrastructure/repository/GoalTeamRepositoryTestFixture.java
> +        유효한_사용자_아이디 = 골에_참여한_사용자_1.getId();
User를 먼저 선언함으로써 `유효한_사용자_아이디`를 실제 생성된 사용자 id를 넣으면 어떨까요?
실제 사용자를 생성하기 전에 `유효한_사용자_아이디`를 1L로 설정해 두는 것은 적절하지 않다고 생각합니다.
만약, 픽스처 수정 혹은 추가 등이 이루어졌을 때 실제로 저장된 값과 픽스처 초기화로 인한 결과가 다를 수도 있을 거란 걱정이 있기 때문입니다.
또한, 실제로 저장한 사용자의 값으로 어차피 다시 초기화해 줄 것이라면, 미리 초기화하지 않고 실제 생성된 사용자의 id로 초기화해 주는 것이 더 이해가 쉬울 것 같다는 생각이 들기도 합니다!

2024-01-15 06:43 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +        this.memo = setNewMemo(memo);
회의에서 논의했던대로 2번 processDefaultName으로 진행하는걸로 해요!!

2024-01-20 18:37 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTerm.java
> +    private long getValidGoalDays(final LocalDate startDate, final LocalDate endDate) {
회의에서 논의했던대로 inProgressDays는 백엔드에서 관리하지 않고 프론트에서 계산하는 것으로 수정하였습니다.

2024-01-20 18:41 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +    @GetMapping(value = "/main", headers = "X-API-VERSION=1")
의견 주신대로 all로 수정하였습니다!

2024-01-20 18:44 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        final ReadAllGoalResponse readAllGoalResponse = new ReadAllGoalResponse(readAllGoalDtos);
dto 생성하는 부분 모두 수정했습니다. 또 dto는 레포지토리에서는 객체 그대로의 결과를 가지고 온 후에 서비스단에서 한 번, 컨트롤러에서 한번 dto로 감싸 클라이언트로 보낼 수 있게 수정했습니다.

2024-01-20 18:45 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/response/ReadAllGoalResponse.java
> +        List<ReadAllGoalDto> readAllGoals
위에서 코멘트 단 것처럼 dto 부분 모두 수정완료했습니다!

2024-01-20 18:48 UTC, jhsseonn commented on src/test/java/com/backend/blooming/goal/infrastructure/repository/GoalTeamRepositoryTestFixture.java
> +        유효한_사용자_아이디 = 골에_참여한_사용자_1.getId();
넵 확인하고 수정했습니다! goalTeamRepositoryTest는 골 팀 레파지토리가 삭제되면서 모두 삭제했고, 다른 테스트 픽스처에서는 모두 직접 객체의 아이디를 가져다 테스트 하도록 수정했습니다.

2024-01-21 06:47 UTC, JJ503 approved these changes
정말 고생 많으셨습니다...!
conversation 개수만 봐도 효선님의 노고가 느껴지네요...
리뷰 사항들에 대해 잘 적용해 주셔서 해당 pr은 이만 approve 합니다!
다만, 머지를 하시기 전에 코드 컨벤션 관련된 사항들과 docs 최신화 부탁드립니다! (goal 문서가 최신화되어 있지 않네요...)

리뷰가 많아 보이지만 대부분 개행과 관련된 리뷰니 부담스러워하지 않으셔도 괜찮습니다! ㅎㅎ
그리고 몇 가지 질문 사항이 있어 해당 부분 확인해 주시면 감사하겠습니다!

2024-01-21 06:47 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/GoalTerm.java
> +                                        final LocalDate endDate) {
### 필수
코드 컨벤션 적용 부탁드립니다!

2024-01-21 06:47 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/GoalTerm.java
> +        return goalDays;
### 필수
return 위에는 개행을 추가해주어야 합니다!

2024-01-21 06:47 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/GoalTerm.java
> +    @FutureOrPresent
사실 해당 부분은 도메인이 아닌 request dto에서 1차 검증을 위해 달아 주면 좋겠다는 의미였는데, 해당 부분이 아닌 도메인에서 검증하게 된 이유가 있을까요?
`validateGoalDatePeriod`라는 메서드와 중복되는 검증이 아닌가 하는 의문이 있어 여쭤봅니다!

2024-01-21 06:47 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        return ResponseEntity.ok().body(response);
이렇게 해줘도 동일한 결과를 냅니다!
```suggestion
        return ResponseEntity.ok(response);
```

2024-01-21 06:47 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/dto/response/ReadAllGoalResponse.java
> +
해당 클래스에도 불필요한 개행들이 몇 곳 보이네요!
혹시 해당 방식을 더 선호하시는 걸까요?

2024-01-21 06:47 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
> +        assertSoftly(softAssertions -> {
### 질문
저는 해당 방식에 대해 하나라는 걸, 3개의 골이라면 각각 id와 name과 같이 식별되는 값으로 총 2가지 값으로 3개의 골을 검증을 하자는 의미였는데 서로 다르게 이해한 것 같습니다..!
혹시 해당 부분에 대해 어떻게 생각하시나요?

2024-01-21 06:47 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/domain/GoalTermTest.java
> +                                                                              .plusDays(2)))
이정도는 개행을 하지 않는 것에 대해 어떻게 생각하시나요?
테스트 코드기도 하고, 오히려 가독성이 안 좋아지는 것 같아서요!

2024-01-21 06:47 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/domain/GoalTestFixture.java
> +                                 .build();
이렇게 진행한다면, 매번 객체를 새로 만들어주지 않아도 돼서 좋은 것 같네요!! 👍

2024-01-21 06:56 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/dto/CreateGoalDto.java
> +                                   final Long managerId) {
넵! 수정한 줄 알았는데 반영이 안되었군요.. 수정하도록 하겠습니다!

2024-01-21 07:20 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    private User getValidUser(final Long userId) {
같은 기능이면 이름 서로 맞추면 좋을 것 같습니다! 오늘 회의 때 한 번 논의해보는걸로 해요!

2024-01-21 07:24 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTerm.java
> +    @FutureOrPresent
앗 @도메인에서의 검증을 의미하는걸로 착각했습니다. request dto에서 검증하는걸로 수정하도록 하겠습니다!

2024-01-21 07:27 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/response/ReadAllGoalResponse.java
> +
코드 짤 때 가독성 면에서 일부러 한 줄 띄우고 시작하긴 했습니다..! 그런데 저희가 이전에 전한 컨벤션이 있어서 컨벤션에 맞게 수정하도록 하겠습니다!

2024-01-21 07:29 UTC, jhsseonn commented on src/test/java/com/backend/blooming/goal/domain/GoalTermTest.java
> +                                                                              .plusDays(2)))
커밋 전에 습관적으로 cmd+shit+l 했는데 개행이 들어간 것 같습니다..! 수정하도록 하겠습니다.

2024-01-21 07:47 UTC, merged