골 수정 및 삭제 기능 구현
Goal-Tracker/blooming-backend pull request #43
Opened 2024-02-01 15:38 UTC by jhsseonn

**2/2**
골 수정 및 삭제 기능 구현 완료했습니다. 우선 예정보다 늦게 pr을 올리게 되어 죄송합니다..
해당 pr도 앞선 브랜치와 마찬가지로 브랜치 새로 파서 해당 pr에서 진행한 커밋내역만 반영하였습니다.

골 수정 관련해서 초기와 바뀐 사항이 있습니다.
초기에는 `put` 메서드를 사용해 변경 이전의 내용과 변경 후의 내용을 합쳐서 프론트에서 보내주면 모두 수정하는 방식으로 진행하려 하였으나,
골 시작날짜와 같이 변경되면 안되는 필드가 존재해 `patch` 메서드를 사용해 현재 변경 가능한 필드만을 `request`로 받아 해당 필드만 `update` 하는 식으로 구현하였습니다.
수정 및 삭제 `api` 문서는 노션에 이번주 회의록 만들어서 올려두었습니다. 확인해주시면 감사하겠습니다!

[작업내역]
- 골 삭제 기능 구현 및 테스트
- 골 수정 기능 구현 및 테스트
- closed #9

2024-02-03 05:02 UTC, JJ503 requested changes
고생 많으셨습니다!
필수로 수정했으면 하는 사항들과 질문들이 있어 일단 rc로 처리해 두었습니다.
이와 함께 컨벤션 부분에서도 확인해주셨으면 해서 함께 확인해 주시면 감사하겠습니다.

2024-02-03 05:02 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +    @DeleteMapping(value = "/{goalId}", headers = "X-API-VERSION=1")
이건 정말 별거 아닌 제안 사항인데, 컨트롤러와 서비스에서 메서드 순서를 C -> R -> U -> D 순으로 하는 것에 대해 어떻게 생각하시나요?

2024-02-03 13:51 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        goalRepository.flush();
엇 변경감지를 생각 못한 것 같습니다! 데이터베이스 내용 수정을 위해선 flush를 해줘야겠다고 생각했는데 JPA는 알아서 변경감지를 하니 필요 없겠군요...

2024-02-03 13:57 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    }
넵 저도 50자가 넘어가면 아예 생성 또는 수정이 불가하게 하는 것이 좋을지, 그래도 50자까지는 저장을 하는 게 좋을지 고민하다가 일단은 저장은 되게 했는데 만약 50자 이상은 아예 저장이 불가하게 한다면 그냥 예외처리 해도 괜찮을 것 같네요! 내일 회의 때 얘기해보고 결정되는 방법으로 수정하도록 하겠습니다!

2024-02-03 13:59 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +    public ResponseEntity<Long> createGoal(
넵 수정하도록 하겠습니다!

2024-02-03 14:03 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        return ResponseEntity.created(URI.create("/goals/" + response.id())).build();
저의 경우에는 수정을 하면 수정된 정보들이 포함된 골 페이지로 넘어간다고 생각을 했습니다. 
수정 페이지에 그대로 있고, 수정 내용들을 보여주는 것보다 더 직관적으로 수정이 완료되었다는 것을 전달할 수 있다고 생각했습니다. 
User 정보 수정은 저희가 지금 마이페이지가 따로 없지 않나요? 그래서 수정 이후 이동할 페이지가 딱히 없어서 수정이 반영된 객체 정보를 그대로 넘겨준 것이라 생각했습니다. 
그래서 저는 지금 상황에서는 둘이 통일하는 것보다는 다르게 가도 괜찮지 않을까 합니다!

2024-02-03 14:03 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/request/UpdateGoalRequest.java
> +        LocalDate endDate,
null 값으로 들어오면 수정을 진행하지 않도록 했습니다!

2024-02-04 09:46 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        goal.updateTeams(users);
생각을 해봤는데 참여자 목록도 수정 내역이 없는 경우엔 `null` 값으로 받고 수정 로직 자체를 실행하지 않는 방식으로 하면 되겠군요..! 해당 논의사항 유진님께 말씀드려보겠습니다!

2024-02-07 02:49 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
>      }
여기 코멘트가 빠졌네요..! 해당 예외의 경우 request가 잘못 들어온 경우라 Bad request로 처리하는 것이 맞는 것 같습니다! 수정하겠습니다.

2024-02-07 07:41 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +
해당 기능은 #49 에서 리팩토링으로 진행하도록 하겠습니다.

2024-02-07 07:44 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    }
골 제목 50자 이상일 경우 추가 또는 삭제가 되지 않도록 구현하는 것으로 하겠습니다. 
수정에서의 검증은 이번 이슈에 반영해서 올리고, 추가에서의 검증은 #49 에서 작업하도록 하겠습니다.

2024-02-07 09:13 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    public void updateTeams(final List<User> users) {
`teams`를 VO처럼 따로 하나의 클래스를 생성하는 것을 말씀하시는걸까요? VO처럼 관리하려니 `OneToMany` 매핑이 걸려서 구현이 다소 어려워 방법을 여쭤봅니다!

2024-02-08 16:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    public void updateTeams(final List<User> users) {
팀원 목록에 대해 검증하고 수정하는 일들이 많다 보니 일급 컬렉션으로 사용하면 좋을 것 같아 제안드렸습니다.
그런데 연관관계 편의 메서드로 인해 좀 어려울 수도 있긴 하겠네요.
생성자는 어색하니, 팩토리 메서드를 통해 Goal도 함께 넘겨주어도 많이 어색할까요?

2024-02-08 16:56 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        return ResponseEntity.created(URI.create("/goals/" + response.id())).build();
이해했습니다!
사용자 수정의 경우 기존에 따로 페이지가 있다기보다는 팝업으로 진행했기에 저도 자연스럽게 페이지보다는 수정된 사용자의 정보를 바로 넘겨줄 수 있도록 진행하게 된 것 같습니다.

그런데 이건 제가 클라이언트 측을 잘 몰라서 그럴 수도 있긴 하지만, 골 수정과 같은 경우에도 페이지의 이동보다는 수정 페이지의 종료 느낌이 강하다고 생각하는 데 어떻게 생각하시나요?
또한, 수정 시 해당 데이터를 바로 넘겨주면 안드로이드 측에서 별도의 요청 없이 수정된 정보를 반영할 수 있습니다.
하지만, 수정 후 수정과 관련된 url을 넘겨주게 된다면 해당 정보를 다시 요청해야 하는 비용이 발생하게 됩니다.
이 부분에 대해서도 어떻게 생각하시는지 궁금합니다!

2024-02-08 17:06 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    public void updateTeams(final List<User> users) {
코멘트를 달고 코드를 확인해 의견을 더 드려보자면 Teams는 굳이 넘길 필요가 없지 않나요?
user와 goal만 넘겨 생성 후 해당 List를 Teams에 할당해주면 어떨까요?

2024-02-08 17:51 UTC, JJ503 requested changes
리뷰 반영하시느라 고생 많으셨습니다!
그런데 아직 좀 더 이야기해보고 싶은 사항 + 수정하면 좋지 않을까 하는 사항이 있어 rc로 처리합니다.
수정과 관련된 경우 필수는 아니고 제안이기에 보시고 괜찮다면 반영 혹은 의견 주시면 감사하겠습니다!

2024-02-08 17:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +            goal.updateTeams(users, goal);
해당 기능을 메서드로 분리하면 어떨까요?
현재 update 메서드의 길이가 너무 길어 제안해 봅니다!

2024-02-08 17:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    }
Goal 생성 시 해당 부분을 검증하는 데 여기서도 검증이 필요할까요?

2024-02-08 17:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    @Transactional
해당 클래스에 `@Transactinal`이 붙어있는데, readOnly가 false인 메서드들에도 붙여준 이유가 궁금합니다!

2024-02-08 17:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/exception/UpdateGoalForbiddenException.java
> +    public UpdateGoalForbiddenException(final ExceptionMessage exceptionMessage) {
해당 부분을 외부에서 사용하지 않고, 자식 클래스에서만 아예 private으로 선언해줘도 좋을 것 같아요!

2024-02-08 17:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +        if (memo.isEmpty()) {
null 검증을 뺀 이유가 궁금합니다! 오히려 `isEmpty()`가 필요 없지 않나 싶기도 하고요.
또한, 해당 부분 테스트 시 `@NullAndEmptySource`를 사용해 테스트를 진행하신다면 더 정확한 결과를 얻을 수 있지 않을까 싶습니다.

2024-02-08 17:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/GoalTerm.java
> +    }
해당 부분은 불가능한거였나요?
회의록을 봤지만 찾지 못해 여쭤봅니다!

2024-02-08 17:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Teams.java
> +    }
해당 생성자가 public으로 필요한가요?
`@NoArgsConstructor(access = AccessLevel.PROTECTED)`
이런 어노테이션을 사용해 줘도 좋을 것 같네요!

2024-02-08 17:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/dto/request/UpdateGoalRequest.java
> +        @FutureOrPresent
`@FutureOrPreset` 조건에 어긋나면 예외가 발생할 것입니다.
그런데 현재는 예외가 발생했을 때 예외 메시지가 따로 없어 어떤 문제인지 확인이 어려울 수도 있을 것 같아요!
아래와 같이 예외 메시지를 추가해 주면 어떨까요?
```suggestion
        @FutureOrPresent(message = "~")
```

2024-02-08 17:51 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/dto/request/UpdateGoalRequest.java
> +        LocalDate endDate,
해당 의미가 Null이 들어와도 `@FutureOrPresent`에서 예외가 발생하지 않는다는 의미가 맞을까요?

2024-02-08 18:19 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +            goal.updateTeams(users, goal);
앗 이 부분을 빼먹었네요! 반영하겠습니다!

2024-02-08 18:21 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    @Transactional
변경감지를 위해 필요하다고 생각했는데 Service 클래스에 이미 붙여주었으니 따로 붙여줄 이유가 없겠네요..! 수정하겠습니다!

2024-02-08 18:23 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTerm.java
> +    }
네 맞습니다. 기존에 저장되어 있던 종료날짜와 비교했을 때 수정하려는 날짜가 더 이전인 경우 수정 불가하게 하자고 했었습니다. 
노션 11월 12일 회의록 참고하시면 좋을 것 같습니다. 캡처본 남깁니다!
<img width="740" alt="스크린샷 2024-02-09 오전 3 22 59" src="https://github.com/Goal-Tracker/blooming-backend/assets/68596746/c90bee61-66d1-4656-915e-ce522d4525f9">

2024-02-08 18:26 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/request/UpdateGoalRequest.java
> +        @FutureOrPresent
좋습니다! 예외메시지 남기도록 하겠습니다!

2024-02-08 18:32 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/request/UpdateGoalRequest.java
> +        @FutureOrPresent
`endDate` `null`값 request에 대해 더 말씀드리자면, 테스트 코드상으로는 `@DateTimeFormat` 및 `@FutureOrPresent`에서도 예외가 발생하지 않고 null 값을 그대로 받아올 수 있었습니다. 실제로 클라이언트와 통신을 했을 때도 오류가 안 나는지는 서버에 올려보고 테스트 해봐야 알 수 있을 것 같습니다.

2024-02-08 18:36 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +        if (memo.isEmpty()) {
구현하면서 `null`과 `isEmpty()`, `isBlank()`의 차이가 궁금해 찾아보았는데 `isEmpty()` 메서드에서 `null` 값 또한 `true`로 반환한다고 해 `isEmpty`로 한꺼번에 처리했습니다. 생각해보니 메모의 경우 빈값이면 그대로 빈값으로 넣어주면 되니 `null`만 검증해도 되겠네요! `null`인지 검증하는 부분만 남겨두도록 하겠습니다.
`@NullAndEmptySource` 사용하는 부분 공부해보겠습니다!

2024-02-08 18:41 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    }
해당 검증 이후 userRepository에서 teamUserIds에 포함된 아이디들에 해당하는 사용자 정보를 조회하는데, 이 때 파라미터로 null 값이 들어가도 되나? 해서 검증을 추가하게 되었습니다. 크기가 5보다 큰지 검증하는 부분은 따로 필요없을 것 같네요.

2024-02-10 05:30 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    }
`teamUserIds.isEmpty() 해당 부분도 사이즈 검증 시 함께 해줘도 되지 않나요?

2024-02-10 05:36 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +        if (memo.isEmpty()) {
`isEmpty`는 `null`인 경우 true를 반환해주지 않습니다.
`ObjectUtils.isEmpty()`와 헷갈리신 것 같아요!
실제로 현재 테스트에 `""` 대신 `null`을 넣으시면 테스트가 실패하는 것을 확인하실 수 있습니다.
그리고 효선님 말씀처럼 해당 경우는 null만 진행해줘도 충분하다고 생각합니다.

그런데 그동안 `isEmtpy()`를 사용한 곳을 `isBlank()`로 수정하는 건 좋을 것 같아요!
당시에는 별 생각 없이 `isEmtpy()`를 사용했는데, 대부분`"   "`와 같은 부분들도 빈 값으로 처리해야 하니까요!
해당 부분 리팩터링 진행할까요?

2024-02-10 05:39 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +        if (memo.isEmpty()) {
그런데, 해당 테스트의 경우 null만 체크하는 것으로 바꿨기 때문에 메모를 `""`이 아닌 `null`로 수정해야 할 것 같습니다.
<img width="461" alt="image" src="https://github.com/Goal-Tracker/blooming-backend/assets/63184334/b7b3c2a6-0bb8-4b36-a6f2-d836540f6e83">

2024-02-10 08:06 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    public void updateTeams(final List<User> users) {
team을 같이 넘겨주지 않고 goal.getTeams()로 할당해줄 경우 goal에 아직 teams가 생성되지 않아 오류가 발생해 teams도 함께 넘겨주었습니다. 이건 Teams를 별도의 클래스로 빼 생성자로 할당해주면서 생긴 문제인 것 같아 팩토리 메서드를 사용했을 때는 어떻게 될지 잘 모르겠네요. 한 번 시도해봐야할 것 같습니다!
그리고 기존에 있던 팀원을 삭제하는 경우는 고도화 단계에서 진행하기로 해서 기존 팀원은 수정할 수 없되, 새로운 팀원은 추가할 수 있도록 구현했습니다.

2024-02-10 08:11 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        return ResponseEntity.created(URI.create("/goals/" + response.id())).build();
수정 페이지를 종료하면서 기존 골 정보 페이지에 수정된 정보를 바로 반영할 수 있으면 url을 넘겨줄 필요가 없겠네요! 페이지 별로 실행시에 무조건 api를 호출해야한다고 생각했어서 수정 후 골 정보 페이지로 나가면 어차피 단일 골 조회 api를 수행하게 될텐데 그러면 url을 바로 넘겨주지 않아도 되지 않을까 생각했던 것 같습니다. 안드로이드 측과 수정 관련해서 좀 더 이야기를 나눠볼 걸 그랬네요..!

2024-02-10 08:13 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/dto/request/UpdateGoalRequest.java
> +        LocalDate endDate,
여기에 달린 코멘트인지 모르고 맨 아래에 덧붙여서 코멘트를 달았네요.. 지금 상태로는 `@FutureOrPresent`에서도 예외가 발생하지 않았습니다!

2024-02-10 10:40 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    }
Teams에서 validateUsersSize 부분 말씀하시는걸까요? 이 부분이 맞다면, 테스트 시에 오류가 발생해 지웠던걸로 기억하는데 방금 다시 테스트 돌려보니 잘 돌아가네요... 해당 검증 추가해주었습니다!

2024-02-10 10:47 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +        if (memo.isEmpty()) {
아하 라이브러리가 달랐군요... 확인을 잘 해야겠네요..! isEmpty()를 사용한 곳을 isBlank()로 수정하는 것 좋습니다! 다음 리팩토링 진행하면서 함께 수정하는 걸로 해요!
골 메모를 빈값으로 받은 경우 비어있는 값으로 저장한다 테스트 부분은 수정하도록 하겠습니다.

2024-02-11 04:16 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    public void updateTeams(final List<User> users) {
제 이야기는 팩토리 메서드와 상관없이, `Teams`에서 this를 통해 넘겨주는 것이 아닌, `GoalTeam` 객체를 생성한 후 그 리스트들을 모아 `Teams`의 `goalTeams` 리스트에 `addAll()`과 같은 메서드를 통해 추가해 주면 되는 것이 아닌 가 하여 의견 드렸습니다.
하지만, `Teams`의 경우 생성자가 일반적인 생성자와 역할 혹은 생성 방식이 조금 다르다고 생각해 팩토리 메서드로 분리하면 좋을 것 같다는 이야기였습니다.
코드로 하면 아래와 같을 것 같습니다.
(다만, 간단하게 작성해본 코드라 참고만 해주시면 될 것 같습니다!)

### Teams
```
    private Teams(final List<GoalTeam> goalTeams) {
        this.goalTeams = goalTeams;
    }

    public static Teams create(final List<User> users, final Goal goal) {
        validateUsersSize(users);
        final List<GoalTeam> goalTeams = users.stream()
                                               .map(user -> new GoalTeam(user, goal))
                                               .toList();

        return new Teams(goalTeams);
    }

    public void updateTeams(final List<User> users, final Goal goal) {
        validateUsersSize(users);
        final List<User> usersBeforeUpdate = this.goalTeams.stream()
                                                           .map(GoalTeam::getUser)
                                                           .toList();
        final List<GoalTeam> goalTeams = users.stream()
                                               .filter(user -> !usersBeforeUpdate.contains(user))
                                               .map(user -> new GoalTeam(user, goal))
                                               .toList();

        this.goalTeams.addAll(goalTeams);
    }
```

### Goal
```
    public GoalTeam(final User user, final Goal goal) {
        this.user = user;
        this.goal = goal;
    }
```

2024-02-11 04:18 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        return ResponseEntity.created(URI.create("/goals/" + response.id())).build();
그렇다면 결론이 어떻게 되는걸까요?

2024-02-11 04:18 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    }
네 맞습니다

2024-02-11 04:19 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +        if (memo.isEmpty()) {
좋습니다!
제 부분에서도 `isEmpty()`를 통해 검증 등을 하는 부분이 있다면 `isBlank()`로 수정할 수 있도록 하겠습니다!

2024-02-13 16:58 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        return ResponseEntity.created(URI.create("/goals/" + response.id())).build();
회의에서 이야기한대로 수정된 내용들을 `response`로 넘겨주도록 하겠습니다!

2024-02-13 16:58 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    }
도움주신대로 `ReflectionUtils`를 사용해 해결했습니다. 감사합니다!

2024-02-13 17:20 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    public void updateTeams(final List<User> users) {
코드 예시 감사합니다! 덕분에 팩토리 메서드에 대해 좀 더 확실히 이해할 수 있었습니다. 코드 참고해서 리팩토링 진행해보았습니다.

2024-02-14 04:40 UTC, JJ503 approved these changes
고생 많으셨습니다!
아주 간단한 수정 사항만 남았기에 이만 approve 합니다~

2024-02-14 04:40 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    }
`goal`을 굳이 파라미터로 받을 필요 없이 `this`로 충분하지 않을까요?

2024-02-14 04:40 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/GoalController.java
> +        return ResponseEntity.noContent().build();
`.build()` 전에 개행 한 번 주면 좋을 것 같네요!

2024-02-14 04:40 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/dto/request/UpdateGoalRequest.java
> +        @FutureOrPresent(message = "종료날짜는 현재보다 과거일 수 없습니다.")
👍

2024-02-15 07:16 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    }
오 그러네요! 수정하도록 하겠습니다!

2024-02-15 07:22 UTC, merged