스탬프 추가 기능 구현
Goal-Tracker/blooming-backend pull request #56
Opened 2024-02-11 10:09 UTC by jhsseonn

**2/11**
스탬프 추가 기능 구현 완료했습니다. 
조회 기능까지 한꺼번에 올리려다 이슈를 스탬프 추가로만 파두어서 추가 먼저 올리고 조회는 따로 올리도록 하겠습니다!
확인하시고 리뷰 부탁드립니다!

[작업내용]
- 새로운 스탬프 생성
- 과거 스탬프도 생성 가능하도록 미래일 경우에만 예외처리

스탬프 테이블이 제대로 생성되지 않는 문제 때문에 쓸데없이 시간을 많이 잡아먹었습니다...
문제 원인은 스탬프 필드명 중 날짜 필드명을 `day`로만 설정했는데 `sql`에서는 예약어가 존재했는지 `sql`에서 `SyntaxError`가 발생해 `day` 필드명을 `sql`에서는 `stamp_day`로 `name` 따로 설정해주니 테이블 정상적으로 잘 생성되었습니다. 이렇게 또 삽질로 배워가네요..

2024-02-11 16:22 UTC, JJ503 requested changes
고생 많으셨습니다!
그런데, 이야기하고 싶은 부분들이 몇 곳 있어 일단 rc로 처리해 둡니다.
또한, 새로운 api에 대한 api 명세서 문서 최신화가 안 되어 있네요.
해당 부분도 확인 부탁드립니다.

2024-02-11 16:22 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/domain/Stamp.java
> +    private static final int STAMP_MESSAGE_MAXIMUM = 50;
매직 넘버 좋네요!
최대 30 자로 변경된 것 리마인드차 작성해 둡니다!

2024-02-11 16:22 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/presentation/StampController.java
> +        return ResponseEntity.noContent().build();
해당 부분을 생성한 스탬프 객체를 반환하기로 한 것도 리마인드차 작성해 둡니다!

2024-02-11 16:22 UTC, JJ503 commented on src/test/java/com/backend/blooming/stamp/domain/StampTest.java
> +    @NullAndEmptySource
👍

2024-02-16 08:13 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +        this.stamps = new ArrayList<>((int) this.goalTerm.getDays());
그러네요..! 초기에 일수별로 스탬프를 만들어야한다고 생각을 해 크기를 할당해주었는데 생각을 잘못했네요. 수정하도록 하겠습니다!

2024-02-16 12:39 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/application/StampService.java
> +        }
엇 이것까진 생각을 못했네요! 수정하겠습니다!

2024-02-16 15:26 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    private List<Stamp> stamps;
처음에 단일 골 조회에서 스탬프까지 모두 조회해오려고 추가를 했는데 이후 골 정보 조회와 스탬프 조회를 서로 다른 api로 통신하는 것으로 변경하게 되면서 필요가 없어진 것 같습니다. 그리고 1:n의 경우 한 개까지만 `fetch join`이 가능한지는 몰랐네요...! 앞으로 참고하도록 하겠습니다. 해당 부분은 삭제하는 것으로 수정하겠습니다!

2024-02-16 15:29 UTC, closed without merging

2024-02-17 06:01 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Goal.java
> +    private List<Stamp> stamps;
[참고 블로그](https://ilovepotato.tistory.com/36)

위 블로그를 참고해 보시면 좋을 것 같아요!
두 개 이상의 컬렉션을 fetch join하게 되면 카테시안 곱이 발생할 수 있기에 이를 JPA가 미리 막아 예외를 발생시켜 불가능하게 됩니다.
물론, 다른 방식으로 해결할 수 있긴 하지만, 지난 회의 때 질문을 드린 결과 `goal`과 `stamp`를 함께 불러오는 경우는 없다고 하셔서 아예 불필요하다고 생각하게 되었습니다!