소셜 로그인 기능 추가
Goal-Tracker/blooming-backend pull request #6
Opened 2023-11-18 18:29 UTC by JJ503

카카오를 통한 소셜 로그인 기능 구현 완료했습니다.
아래는 이해를 돕고자 소셜 로그인과 관련해 대략적인 플로우를 작성해 보았습니다.
구현을 진행하면서 구현 자체보다는, 구현 방식을 선택한 이유에 대한 고민이 좀 길어져 제가 생각한 시간보다 늦어졌습니다.
선택한 이유에 대해서는 다음 주까지는 디스커션을 통해 올릴 수 있도록 하겠습니다.

### 신규 회원 소셜 로그인 플로우
1. 안드로이드 측으로부터 카카오 access token을 받음
2. 해당 access token을 사용해 카카오 외부 api로 사용자 정보 조회 (서비스 회원 번호, 사용자 이메일)
3. 받은 정보와 함께 사용자 저장 (서비스 회원 번호와 동일한 데이터가 없다 가정)
4. 저장한 사용자 아이디를 통해 서비스 자체 jwt 토큰 생성 후 전달 (access token: 12시간, refresh token: 2달 -> 카카오와 동일)
5. 위 정보와 함께 isSignUp이 참으로 전달되어 안드로이드 측에서 회워가입을 위한 추가 정보를 받아 사용자 정보 수정 api를 통해 서버에 전달
6. 추가 정보를 수정 기능을 통해 업데이트 후 사용자 정보 반환
7. 메인 페이지로 이동

### 기존 회원 소셜 로그인 플로우
1. 안드로이드 측으로부터 카카오 access token을 받음
2. 해당 access token을 사용해 카카오 외부 api로 사용자 정보 조회 (서비스 회원 번호, 사용자 이메일)
3. 서비스 회원 번호를 통해 사용자 정보 조회
4. 조회한 사용자 정보 중 아이디를 통해 서비스 자체 jwt 토큰 생성 후 전달 (access token: 12시간, refresh token: 2달 -> 카카오와 동일)
5. 위 정보와 함께 isSignUp이 거짓으로 전달되어 안드로이드 측에서 바로 메인으로 이동하도록 함

### 로그인 후 각 api 요청에 대한 인가 플로우
1.  사용자 권한이 필요한 경우는 API 헤더를 통해 사용자 access token을 전달받음
2. `interceptor`를 통해 token 파싱해 토큰이 유효한지만 확인 (유효하지 않다면 오류 발생으로 종료)
3. `argumentResolver`를 통해 토큰에서 파싱한 정보인 사용자 아이디를 갖고 AuthenticatedUser를 생성해 반환해 사용하도록 함
   (`@Authenticated AuthenticatedUser authenticatedUser`)
 
## 함께 이야기해보고 싶은 내용
- todo로 작성해두었는데, 테스트 작성 시 `@Nested`를 사용하는 것에 대해 어떻게 생각하시는 지 궁금합니다.
  저도 생각이 아직 정리가 안 된 상태이지만, 이런 방식도 있다는 느낌으로 언급해보았습니다.
- 컨트롤러 테스트의 경우 restDocs를 위해 `@WebMvcTest`를 사용하고 있습니다. 그래서 사실상 컨트롤러 테스트의 경우 정말 api의 흐름정도만 테스트하고 있다고 볼 수 있습니다. 그래서 이 부분에 대해서도 어떻게 생각하시는 지 궁금합니다.

2023-11-19 09:02 UTC, jhsseonn approved these changes
리뷰 완료했습니다!
컨벤션에서 수정할 부분은 없어보이고 간단한 질문 몇개만 남겼습니다.
이대로 머지하셔도 괜찮을 것 같습니다!

2023-11-19 13:24 UTC, jhsseonn commented
> 전체적인 테스트 네이밍, fixture 등 방식에 대한 논의가 필요하다고 생각합니다.
**`fixture` 클래스 관리**
- 한 도메인에 하나의 fixture를 둘 것
- 각 테스트 클래스 별로 fixture 분리하기로 함.
**`fixture`로 분리할 범위**
- `given` 절에 들어가는 모든 변수들
- fixture 변수의 경우 한글로 작성
- 도메인 테스트의 경우에만 테스트의 대상인 `도메인`은 fixture로 구분하지 않기로 함.

> todo로 작성해 두었는데, 테스트 작성 시 @Nested를 사용하는 것에 대해 어떻게 생각하시는지 궁금합니다.
> 저도 생각이 아직 정리가 안 된 상태이지만, 이런 방식도 있다는 느낌으로 언급해 보았습니다.
회의 결과 `@Nested`는 일단 사용하지 않기로 함

> 컨트롤러 테스트의 경우 restDocs를 위해 @WebMvcTest를 사용하고 있습니다. 그래서 사실상 컨트롤러 테스트의 경우 정말 api의 흐름정도만 테스트하고 있다고 볼 수 있습니다. 그래서 이 부분에 대해서도 어떻게 생각하시는지 궁금합니다.
`ControllerTest`의 인수 혹은 통합 테스트는 추후 필요하다 느껴지면 다시 논의해보는 걸로 합시다!

2023-11-30 17:56 UTC, jhsseonn requested changes
컨벤션 및 오타 위주로 리뷰 남겼습니다. 코멘트 단 부분을 제외하고는 수정할 사항이 보이지 않아서 간단한 오타 수정 후 바로 머지해도 될 것 같습니다!

2023-11-30 17:56 UTC, jhsseonn commented on src/main/java/com/backend/blooming/authentication/presentation/interceptor/AuthenticationInterceptor.java
> +    private void validateExistUser(final Long userId) {
존재하는 유저인지 검증하는 로직이 위에도 있었는데 클래스마다 따로 생성해준 이유가 궁금합니다!

2023-11-30 17:56 UTC, jhsseonn commented on src/test/java/com/backend/blooming/user/infrastructure/repository/UserRepositoryTest.java
> +    void 존재하지_않는_oauth_아이디를_통해_사용자를_찾으면_반_optinal을_반환한다() {
여기도 오타가 있는 것 같네요!

2023-12-02 05:29 UTC, JJ503 commented on src/main/java/com/backend/blooming/authentication/configuration/RestTemplateConfiguration.java
> +        return new RestTemplate();
네 굳이 필요 없다고 생각합니다.
return을 개행하는 것은 가독성 측면에서 다른 로직들과 구분하기 위한 것으로 저는 이해했습니다.
하지만, 해당 메서드의 경우 다른 로직이 존재하지 않기 때문에 불필요하다고 생각했습니다.

2023-12-02 05:34 UTC, JJ503 commented on src/main/java/com/backend/blooming/user/presentation/UserController.java
> +    @PatchMapping(headers = "X-API-VERSION=1")
Patch를 사용한 이유는 모든 정보가 아닌 수정하고자 하는 정보만 수정하고자 하는 정보만 수정할 것이기 때문입니다.
올려둔 api 명세서를 확인해 보시면, 수정하려는 데이터 외에는 null로 전달하기로 민지님과 이야기되었습니다.
즉, 수정 시 모든 데이터를 수정하는 것이 아니라 사용자가 수정하고자 하는 데이터만 업데이트하게 됩니다.
그런 측면에서는 put과 patch 중 patch가 더 적절하다고 생각했습니다.

2023-12-02 05:48 UTC, JJ503 commented on src/main/java/com/backend/blooming/authentication/presentation/interceptor/AuthenticationInterceptor.java
> +    private void validateExistUser(final Long userId) {
위 메서드라 하면 `isNotExist`을 말씀해 주시는 게 맞을까요?
맞다면, 해당 메서드의 경우 존재하는 유저인지 여부가 아닌 `accessToken`을 사용자가 전달했는지 확인하는 부분입니다.
ArgumentResovler의 경우 `@Authenticated`를 통해 해당 reolver를 수행할지 말지 결정할 수 있지만, Interceptor는 어디서 사용될지 모르는 상태로 모든 경우 수행하게 됩니다.
그래서 accessToken이 필요 없는 경우에도 사용되어야 하므로, Interceptor에서 accessToken이 없는 경우에는 무조건 true를 반환하도록 설정했습니다.

2023-12-02 05:51 UTC, JJ503 commented
리뷰 적용 완료했습니다.
그리고 추가적으로 잘못된 부분이 몇 가지 있어 수정했습니다.
- 잘못된 properties 네이밍 수정
- AuthenticationController의 잘못된 HTTP Method 수정

2023-12-05 11:53 UTC, jhsseonn approved these changes
모든 수정사항 확인했습니다! 더 수정할 부분은 없는 것 같습니다. 머지하셔도 될 것 같습니다.

2023-12-13 09:15 UTC, merged