사용자 정보 수정 시 이름 중복 문제에 대한 예외 처리 추가
Goal-Tracker/blooming-backend pull request #66
Opened 2024-02-16 18:05 UTC by JJ503

- closed #63 

사용자 이름 수정 시 이미 존재하는 이름인지 예외 처리를 따로 하지 않아 추가해 두었습니다.
다만, 자신의 기존 이름으로 수정하는 경우는 예외 없이 정상 작동하는 것으로 보이도록 했습니다.

2024-02-17 17:35 UTC, jhsseonn requested changes
일이 있어 리뷰가 늦어져 죄송합니다..! 
추가하신 부분 모두 확인했습니다. 
`userControllerTest`에서 테스트명에 의문이 있어 rc로 남겨두겠습니다.

2024-02-17 17:35 UTC, jhsseonn commented on src/main/java/com/backend/blooming/user/application/exception/DuplicateUserNameExcpetion.java
> +
개행이 한줄 더 들어간 것 같네요!

2024-02-17 17:35 UTC, jhsseonn commented on src/test/java/com/backend/blooming/user/presentation/UserControllerTest.java
> +
개행이 한줄 더 들어간 것 같네요!

2024-02-17 17:35 UTC, jhsseonn commented on src/test/java/com/backend/blooming/user/presentation/UserControllerTest.java
> +    void 이미_존재하는_이름으로_사용자_정보_수정시_404를_반환한다() throws Exception {
`bad request`로 응답이 가면 400을 반환하지 않나요?

2024-02-17 18:37 UTC, JJ503 commented on src/test/java/com/backend/blooming/user/presentation/UserControllerTest.java
> +    void 이미_존재하는_이름으로_사용자_정보_수정시_404를_반환한다() throws Exception {
헉 맞습니다!!
400으로 수정해 두었습니다. 감사합니다!

2024-02-18 08:02 UTC, jhsseonn approved these changes
수정사항 모두 확인했습니다. approve 하겠습니다!

2024-02-20 06:46 UTC, merged