콕 찌르기 및 알림 전송 추가
Goal-Tracker/blooming-backend pull request #69
Opened 2024-02-17 16:37 UTC by JJ503

- closed #68 

콕 찌르기 기능의 경우 알림을 보내는 게 끝이기에 다른 이슈로 빼기가 애매하다 판단해 함께 진행하겠습니다.
콕 찌르기 및 알림 관련 내용에 대해선 `3차 스프린트 1주차` 회의록에 작성해 두었습니다. 확인해 주시면 감사하겠습니다!
또한, `TODO`를 통해 고민을 한 가지 작성했는데 내용은 아래와 같습니다.
코드는 `TODO`를 검색해 확인하시면 보다 편하게 확인하실 수 있습니다.

### 고민
1. 콕 찌르기 API의 컨트롤러 코드가 URI 상 골 패키지 내에 있는 것이 적절하다고 생각했는데, 어떻게 생각하시는지 궁금합니다.

2024-02-19 11:37 UTC, jhsseonn requested changes
고생 많으셨습니다!
대부분 간단한 컨벤션 수정이고, 골 초대 알림 보내기의 경우 골 팀원 수정시에 추가된 팀원에게도 보내야해서 추가로 구현이 필요할 것 같아 rc로 남깁니다.
그리고 아래는 질문주신 고민에 대한 답변입니다.

1. 콕 찌르기 uri는 저도 좋은 것 같습니다. 코멘트에도 적어두었지만, 지금의 uri가 프론트쪽에서도 구별이 쉬울 것 같습니다. 오히려 스탬프 조회쪽에서도 이렇게 uri를 설정하는 것이 좋은지 고민하게 되네요..! 스탬프도 `goals/{goalId}/stamp` 와 같은 형식이 나을지 질문드립니다!
2. 팀원 목록을 가져오는 로직이 `Goal`과 관련된 로직이어서 저는 `Goal`에 있으면 좋을 것 같습니다!

2024-02-19 11:37 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/presentation/PokeController.java
> +    // TODO: 2/17/24 API의 URI 상 이 패키지가 적절하다고 생각했는데, 괜찮을까요?
전 좋은 것 같습니다! 확실히 잘 구별되는 것 같아서 좋은 것 같습니다. 
다만 제가 이번 스탬프 조회 기능을 구현하면서 stamps/{goalId} 이런 식으로 api 패키지를 설정했는데, 부적절하다고 판단되면 수정하도록 하겠습니다!

2024-02-19 11:37 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        notificationService.sendRequestGoalNotification(goal);
골 팀 목록 수정시에도 `sendRequestGoalNotification`을 해줘야할 것 같습니다! 
이 부분은 골 수정/삭제 부분 머지가 늦어지는 바람에 `develop`에 포함이 안되어 있었던 것 같네요...

2024-02-19 11:37 UTC, jhsseonn commented on src/test/java/com/backend/blooming/goal/application/PokeServiceTestFixture.java
> +                                    .build();
final 붙여줘야겠군요...! 리팩토링 진행하면서 수정하도록 하겠습니다!

2024-02-19 11:37 UTC, jhsseonn commented on src/test/java/com/backend/blooming/notification/application/NotificationServiceTest.java
> +import org.assertj.core.api.*;
별이 보이네요!

2024-02-20 06:57 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/presentation/PokeController.java
> +    // TODO: 2/17/24 API의 URI 상 이 패키지가 적절하다고 생각했는데, 괜찮을까요?
해당 리뷰를 먼저 보지 못하고, [효선님 pr을 리뷰](https://github.com/Goal-Tracker/blooming-backend/pull/71#discussion_r1494573106)해 동일한 의견이 있는 줄 몰랐네요..!
저도 효선님과 동일하게, `/goals/{goalId}/stamps`가 더 자연스럽지 않나? 하는 의문이 있었습니다.
그래서 uri 상 위 형태가 되면 더 좋겠다는 생각을 했습니다.
다만, 그랬을 때 스탬프 관련 코드들을 골로 옮겨야 할까? 하는 고민이 있었습니다.
해당 부분에 대해 어떻게 생각하시나요?

p.s. 스탬프와 관련된 이야기니, 해당 pr에 의견을 작성해주시면, 나중에 다시 확인하고 싶을 때 빨리 찾을 수 있을 것 같습니다!

2024-02-20 07:04 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        notificationService.sendRequestGoalNotification(goal);
그렇네요!
그런데, 해당 부분을 진행하려면 `update()`를 통해 추가된 팀원이 누구인지 알아야 합니다.
그래서 `updateTeams()`를 void가 아닌 `List<GoalTeam>`을 반환하게 하면 어떨지 의견 구하고 싶습니다.
해당 부분은 효선님의 의견을 구한 뒤 결정된 방법으로 수정 진행하려 합니다.
또한, 다른 `update` 메서드들과는 다르게 `updateTeams`만 반환값이 있어도 괜찮은지에 대한 질문을 드리고 싶기도 합니다.

2024-02-21 08:09 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        notificationService.sendRequestGoalNotification(goal);
좋습니다! 수정 로직 구현 과정에서 추가된 팀원을 반환해야하는 경우가 딱히 없을거라 판단해 반환값을 주지 않았는데 이 경우에는 수정된 내용을 반환받아야겠네요. `updateTeams`와 `updateTeams()`에 반환값을 부여하는 것에 동의합니다. 그럼 이 부분은 제가 리팩토링 pr을 파서 수정을 하겠습니다!

2024-02-21 08:10 UTC, jhsseonn approved these changes
수정사항 모두 확인했습니다! `approve` 하겠습니다!

2024-02-21 09:08 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        notificationService.sendRequestGoalNotification(goal);
간단한 수정 사항이기에 이번 pr에서 제가 진행하도록 하겠습니다!

2024-02-22 22:18 UTC, JJ503 commented
위 코멘트에서 이야기한 대로, 골 업데이트에 대해 반환값을 만들어, 이에 해당하는 사용자들에게만 알림을 보내도록 수정했습니다.

2024-02-22 22:21 UTC, merged