스탬프 조회 기능 구현
Goal-Tracker/blooming-backend pull request #71
Opened 2024-02-18 07:22 UTC by jhsseonn

**2/18**
스탬프 조회 기능 구현 완료했습니다. 
단일 스탬프 조회도 필요한가? 고민했는데 유진님께 여쭤보니 바텀 네비게이션으로 단일 정보만 따로 보여준다고 하셔서 api를 또 호출하는 것보다는 한번 조회할 때 모든 정보를 가져와 화면에 보여줄 수 있도록 하는 것이 좋을 것 같아 `단일 골에 대한 모든 스탬프 정보 조회`에서 한번에 가져오도록 구현하였습니다.

[작업내용]
- 단일 골에 대한 모든 스탬프 정보 조회
    - 사용자가 스탬프를 추가하고자 하는 골이 존재하는 골인지, 요청한 사용자가 존재하는 사용자인지에 대한 검증만 추가했습니다. 지난 회의에서 논의한대로 요청 사용자가 현재 골 참여자인지 아닌지 검증하는 부분은 제외하였습니다.
    - 응답 스탬프 정보
        - 사용자 아이디, 이름, 색상, 스탬프 인증 메시지, 스탬프를 찍은 날짜
- 골 참여자들의 스탬프 업로드 여부 조회 - 콕 찌르기를 위한 상태 조회
    - 해당 기능은 콕 찌르기 기능을 위한 오늘 하루동안 참여자들의 스탬프 업로드 여부를 조회하는 기능입니다. 단일 골 조회에서 함께 조회할 수 있도록 구현했습니다. 스탬프에서 조회하기에는 응답의 형태가 골 진행날짜를 key로, 사용자들의 스탬프 정보를 value 값으로 한 map의 형태로 넘겨주고 있는데 스탬프 업로드 여부를 함께 넘겨주기에는 어색하다고 생각해(과거의 경우에는 상태가 필요없기 때문입니다.) 골 조회에서 골 참여자 정보 조회를 하면서 함께 넘겨주는 방식으로 구현했습니다.
- closed #57

2024-02-19 14:02 UTC, JJ503 commented on src/test/java/com/backend/blooming/stamp/presentation/StampControllerTest.java
> +                )
동일한 내용을 두 번 작성할 필요는 없다고 생각하시는 데 어떻게 생각하시나요?
1, 2가 아니라 여기도 *로 표현해 줘도 괜찮지 않나 싶습니다!
저는 아래와 같은 형태를 생각해 봤습니다!

```suggestion
                        fieldWithPath("stamps").type(JsonFieldType.OBJECT).description("날짜별 스탬프 목록"),
                        fieldWithPath("stamps.*").type(JsonFieldType.ARRAY).description("특정 날짜에 대한 스탬프 배열"),
                        fieldWithPath("stamps.*.[].userId").type(JsonFieldType.NUMBER).description("스탬프를 찍은 사용자 아이디"),
                        fieldWithPath("stamps.*.[].name").type(JsonFieldType.STRING).description("스탬프를 찍은 사용자 이름"),
                        fieldWithPath("stamps.*.[].color").type(JsonFieldType.STRING).description("스탬프를 찍은 사용자 프로필 색상코드"),
                        fieldWithPath("stamps.*.[].message").type(JsonFieldType.STRING).description("스탬프를 찍은 사용자 프로필 색상코드"),
                        fieldWithPath("stamps.*.[].day").type(JsonFieldType.NUMBER).description("스탬프를 찍은 날짜")
```

2024-02-19 14:04 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/presentation/dto/response/ReadAllStampResponse.java
> +            int day
day가 꼭 있어야 하나요?

2024-02-23 14:01 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +        final long nowGoalDay = ChronoUnit.DAYS.between(goal.getGoalTerm().getStartDate(), LocalDate.now()) + COUNT_GOAL_DAYS;
좋은 것 같습니다! 해당 부분 따로 클래스로 빼도록 하겠습니다!

2024-02-24 11:07 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/presentation/dto/response/ReadAllStampResponse.java
> +            int day
day가 없으면 day별로 `grouping`을 할 수가 없어서 day를 넣었습니다. day 정보를 빼려면 map 변수를 만들어놓고 해당하는 날짜키의 값 리스트에 추가해주는 식으로 구현을 따로 해야할 것 같습니다. day 정보를 빼는 것이 좋을까요?

2024-02-24 11:07 UTC, jhsseonn commented on src/test/java/com/backend/blooming/stamp/presentation/StampControllerTest.java
> +                )
*로 처리하는 방법을 몰랐네요..! 이렇게 해보겠습니다. 감사합니다!

2024-02-24 11:11 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/presentation/StampController.java
> +    @GetMapping(value = "/{goalId}", headers = "X-API-VERSION=1")
저도 그렇게 생각해서 `/goal/{goalId}/stamp` 로 바꾸도록 하겠습니다! 다만 스탬프 컨트롤러 내용이 골 컨트롤러에 들어가는 것보다는 스탬프 컨트롤러 `RequestMapping`을 `/goals/{goalId}`로 하는 것이 좋을 것 같은데 어떻게 생각하시나요? 지금으로서는 골의 하위 스탬프를 가져오는 것 외에는 따로 스탬프 관련한 기능이 없는 것 같아서 제안드립니다!

2024-02-24 11:22 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/infrastructure/repository/StampRepository.java
> +            WHERE s.day.day = :day AND s.deleted = FALSE
좋습니다! 저도 `s.day.day`는 이해하기 어려울 수도 있겠다는 생각이 드네요. 수정하도록 하겠습니다.

2024-02-24 11:29 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
>          validateUserToUpdate(goal.getManagerId(), user.getId());
좋습니다! 비교 검증하는 부분이 도메인 로직에 더 가까운 것 같네요.

2024-03-03 05:17 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/application/StampService.java
> +        getUser(userId);
다시 조회 시 검증하도록 수정한 것이 맞죠?
헷갈리지 않게 기록해 두려고 확인차 여쭤봅니다!

2024-03-03 05:35 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/presentation/StampController.java
> +    @GetMapping(value = "/{goalId}", headers = "X-API-VERSION=1")
해당 내용 확인했고 좋은 것 같습니다!

2024-03-03 05:49 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/presentation/dto/response/ReadAllStampResponse.java
> +            int day
Dto을 통해 먼저 grouping하고 이를 response로 변환하는 것에 대해 생각해 봤습니다.
그런데 해당 부분이 더 귀찮을 것 같고, day를 넘겨주더라도 이상함은 없을 것 같아 큰 문제는 없을 것 같네요!

2024-03-03 06:19 UTC, JJ503 requested changes
리뷰 반영하시느라 고생 많으셨습니다!
그런데 몇 가지 의문점과 수정했으면 하는 부분들이 있어 rc로 처리해둡니다!

2024-03-03 06:19 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/application/StampService.java
>      }
여기도 `goal`의 `isTeam`을 사용하면 더 좋겠네요!

2024-03-03 06:19 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/application/StampService.java
> +    }
여기도 `isTeam`을 사용하면 더 좋겠네요!

2024-03-03 06:19 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/application/dto/ReadAllStampDto.java
> +                    stamp.getDay().getValue()
해당 부분은 vo니까 stamp에서 `getMessage`, `getDay`를 하면 바로 가져올 수 있도록 하면 어떨까요?
또한, `Message`의 경우 `Message` 객체 내의 필드는 `message`가 아닌 `value`라면 더 좋겠네요!

2024-03-03 06:19 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/infrastructure/repository/StampRepository.java
> +            JOIN FETCH s.goal sg
id는 fetch join과 상관없다고 알고 있는데 아닐까요?

2024-03-03 06:19 UTC, JJ503 commented on src/main/java/com/backend/blooming/utils/days/DayUtil.java
> +        return (int) ChronoUnit.DAYS.between(startDate, endDate) + COUNT_GOAL_DAYS;
이건 그냥 궁금한 점인데, int형으로 변환시켜준 이유가 있을까요?

2024-03-03 06:19 UTC, JJ503 commented on src/main/java/com/backend/blooming/utils/days/DayUtil.java
> +        return (int) ChronoUnit.DAYS.between(startDate, endDate) + COUNT_GOAL_DAYS;
또한, 해당 클래스를 `common` 패키지에 넣어주면 좋을 것 같습니다!

2024-03-03 06:19 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/application/StampService.java
> +import java.util.Optional;
해당 import문은 사용하지 않는 것으로 보이네요!

2024-03-03 06:19 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/presentation/dto/response/ReadAllStampResponse.java
> +import com.backend.blooming.themecolor.domain.ThemeColor;
해당 import문은 사용하지 않는 것으로 보이네요!

2024-03-03 11:31 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/application/StampService.java
> +        getUser(userId);
네 맞습니다! 조회 시 참여자 검증 다 거치도록 수정했습니다!

2024-03-03 11:32 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/infrastructure/repository/StampRepository.java
> +            JOIN FETCH s.goal sg
엇 이건 알아봐야겠네요..! 더 찾아보도록 하겠습니다!

2024-03-16 11:07 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +
어머 getUser인줄 알았네요...! 다시 올려두도록 하겠습니다!

2024-03-16 11:19 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/application/dto/ReadAllStampDto.java
> +                    stamp.getDay().getValue()
좋습니다! message, day 모두 stamp에서 바로 getMessage, getDay로 가져올 수 있도록 수정했습니다! Message 필드도 value로 수정했습니다.

2024-03-16 11:23 UTC, jhsseonn commented on src/main/java/com/backend/blooming/utils/days/DayUtil.java
> +        return (int) ChronoUnit.DAYS.between(startDate, endDate) + COUNT_GOAL_DAYS;
아무래도 숫자형 변수 타입은 아이디를 제외하면 웬만하면 int로 통일하는 것이 좋지 않을까 해서 Int로 변형해주었습니다. 패키지는 common으로 변경해주었습니다!

2024-03-16 11:24 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/presentation/dto/response/ReadAllStampResponse.java
> +            int day
그럼 우선 지금 구현한 방식 그대로 두겠습니다!

2024-03-16 13:42 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/infrastructure/repository/StampRepository.java
> +            JOIN FETCH s.goal sg
혹시 찾아보셨을까요?

2024-03-16 14:17 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/infrastructure/repository/StampRepository.java
> +            JOIN FETCH s.goal sg
네! 앗 여기 진행사항 적는 걸 깜빡했네요..! 
아이디만 가져오는 경우에는 `fetch join`을 사용하지 않아도 효율적으로 처리된다고 gpt가 알려주길래 `fetch join` 제외하고 테스트 해보니 잘 돌아가서 `fetch join` 삭제하는 방식으로 진행했습니다.

2024-03-16 14:46 UTC, JJ503 commented on src/main/java/com/backend/blooming/utils/days/DayUtil.java
> +        return (int) ChronoUnit.DAYS.between(startDate, endDate) + COUNT_GOAL_DAYS;
보통 int로 변환시켜 사용한다면 상관없지만, 그냥 int로 통일하고 싶다는 의미는 크게 와닿지 않습니다.
int와 long의 차이는 다른 것이 아니라 값의 범위입니다.
그런데, 해당 라이브러리에서 해당 메서드의 반환값을 long으로 반환한다면 이유가 있지 않을까 싶어 질문드리게 되었습니다.
int로 변환해 주어도 상관없을까요?

2024-03-16 15:55 UTC, JJ503 requested changes
리뷰 적용하시느라 고생 많으셨습니다!
그런데 마지막으로 확인하고 싶은 부분들이 있어 rc 해둡니다.
이전 리뷰에 대한 코멘트에도 추가 질문이 있으니 확인해주시면 감사하겠습니다!

2024-03-16 15:55 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/application/StampService.java
> +        if (!goal.isTeam(user)) {
`isTeam`이 아닌 수락되었는지도 확인해야 하지 않나요?

2024-03-20 12:17 UTC, jhsseonn commented on src/main/java/com/backend/blooming/common/days/DayUtil.java
> +    }
`common/util` 패키지에 두었습니다!

2024-03-20 12:17 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
감사합니다! 이슈 생성해두겠습니다!

2024-03-20 12:35 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/application/StampService.java
> +        if (!goal.isTeam(user)) {
스탬프쪽이 반영이 안되었군요...! 스탬프 추가/조회도 모두 골 수락한 사용자들만 가능하도록 기능 추가했습니다!

2024-03-22 07:56 UTC, JJ503 requested changes
몇 까지 의견이 더 있어 추가해 보았습니다.

2024-03-22 07:56 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/application/exception/ForbiddenToReadStamp.java
> +public class ForbiddenToReadStamp extends BloomingException {
클래스명에서 `Exception`을 제거한 이유가 있을까요?

2024-03-22 07:56 UTC, JJ503 commented on src/test/java/com/backend/blooming/stamp/presentation/StampControllerTestFixture.java
> +import com.backend.blooming.themecolor.domain.ThemeColor;
해당 import문은 사용하지 않는 것으로 보이네요!

2024-03-22 07:56 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/presentation/dto/response/ReadAllStampResponse.java
> +                          .collect(Collectors.groupingBy(StampInfoResponse::day));
아래처럼 stream을 합칠 수 있을 것 같네요!

```suggestion
        final Map<Integer, List<StampInfoResponse>> stamps = 
                readAllStampDto.stamps()
                               .stream()
                               .map(StampInfoResponse::from)
                               .collect(Collectors.groupingBy(StampInfoResponse::day));
```

2024-03-22 11:05 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/application/exception/ForbiddenToReadStamp.java
> +public class ForbiddenToReadStamp extends BloomingException {
아뇨...!!!! 왜 Exception이 없어졌을까요... 수정하겠습니다.

2024-03-22 11:56 UTC, jhsseonn commented on src/main/java/com/backend/blooming/utils/days/DayUtil.java
> +        return (int) ChronoUnit.DAYS.between(startDate, endDate) + COUNT_GOAL_DAYS;
`ChronoUnit.DAYS.between` 메서드가 `long`으로 값을 반환해주는 이유는 시간에 따른 날짜 데이터이기 때문에 그 수가 기하급수적으로 커질 수 있어서 `long`으로 반환하는 것 같습니다. 그런데 블루밍 서비스에서는 사실 그렇게까지 시간 간격이 길어질 일이 잘 없고, 계산해보니 `int`로 나타낼 수 있는 범위도 충분히 길어서(계산해보니 5,883,516년 정도 나오더라구요) `int`로 변환해주어도 무방할 것 같다는 것이 저의 생각입니다. 어떻게 생각하시나요?

2024-03-22 13:23 UTC, JJ503 commented on src/main/java/com/backend/blooming/utils/days/DayUtil.java
> +        return (int) ChronoUnit.DAYS.between(startDate, endDate) + COUNT_GOAL_DAYS;
저는 그냥 그래야 하는 필요성을 느끼지 못하겠급니다.
만약 데이터가 잘못 들어어면 그에 대한 처리는 어떻게 할까요?
또한, 저희 서비스가 현재 그정도로 크지 않은 날짜 데이터를 사용한다 하더라도 그게 long을 굳이 int로 변환해야 하는 이유를 잘 모르겠습니다..!

2024-03-22 14:59 UTC, jhsseonn commented on src/main/java/com/backend/blooming/utils/days/DayUtil.java
> +        return (int) ChronoUnit.DAYS.between(startDate, endDate) + COUNT_GOAL_DAYS;
우선 `int`로 형변환을 해주게 된 가장 큰 이유는 도메인 필드 타입을 바꿔줘야 한다는 것이었는데 처음 설계할 때 골 날짜수 필드 타입을 `int`로 설정했고, 여기에 맞춰서 `ChoronoUnit.DAYS.between` 메서드의 리턴값도 `int`로 바꿔주었던 것입니다. 골 날짜수 구하는 로직 짤 때 당시에 기존에 설정해둔 타입대로 메서드 리턴값 형변환만 해주면 되는데 `long`으로 설정하게 되면 현재 코드에 있는 모든 골 날짜수 타입을 전부 `long`으로 바꿔주어야해서 `int`를 선택했습니다. 이런 이유 때문에 `long`으로 바꾸는 것을 더 고민하고 있었습니다.
그래서 혹시 데이터가 잘못 들어왔을 때 에러가 날 경우가 있을까 해서 시도를 해봤는데 `int -> long`은 따로 설정해주지 않아도 알아서 변환되는데 `long -> int`는 코드 짤 때 형변환 조건을 다 붙여줘야 하더라구요. 만약 데이터가 `long`으로 들어왔을 때 `int`로 설정해두었으니 이 때는 에러가 발생할 것 같아서 문제가 생길 여지를 주지 않을거라면 `long`으로 설정하는게 맞을 것 같습니다.
그래서 날짜수 데이터는 전부 `long`으로 바꾸도록 하겠습니다!

2024-03-22 15:59 UTC, JJ503 commented
수정 확인 완료했습니다.
고생 많으셨습니다!!

2024-03-22 16:01 UTC, JJ503 approved these changes
수정 확인 완료했습니다.
고생 많으셨습니다!!

2024-03-22 16:23 UTC, merged