S3 연동 및 프로필 이미지 추가
Goal-Tracker/blooming-backend pull request #79
Opened 2024-03-02 18:56 UTC by JJ503

- closed #74 

S3 연동을 통한 프로필 이미지 저장하기 기능 추가했습니다.
이와 함께 보안 및 성능을 위해 cloudfront도 함께 적용했습니다.
cloudfront의 지정 도메인도 설정해야 하는데, 이 부분은 추후에 함께 이야기하고 결정하기 위해 아직 설정하지 않았습니다.
다만, pr merge는 안드로이드 측에서 이미지 업로드가 완료된 후에 가능할 것 같습니다. (api의 변화로 인해)

질문드리고 싶은 부분이 몇 가지 있습니다.
1. 기본 이미지 url에 대해 User 객체에 그냥 상수로 적용했는데, 괜찮을까요?
다른 방식도 고민해 봤지만, 가장 쉬운 방식이라 판단해 그렇게 진행했습니다.
2. S3는 ec2에서만 사용하거나, accessKey와 secretKey가 있어야 사용이 가능합니다.
그런데 보안상 accessKey와 secretKey를 노출시킬 수 없기에 로컬 서버에서는 S3를 사용할 수 없게 됩니다.
그래서 이를 대체하기 위해 `LocalStackContainer`라는 것을 통해 로컬에서 가짜 S3 버킷을 사용할 수 있도록 했습니다.
이를 사용하는 것은 단점은 로컬 서버 수행과 테스트 시 속도가 조금... 느려졌다는 점입니다.
로컬 서버 자체는 사용하는 게 좋을 것 같은데, 테스트에서 잘 되는 게 확인되었으니 mock 객체를 사용해 테스트 속도를 높이는 것이 좋을지 그래도 제대로 수행되는 것을 검증하기 위해 현재처럼 `LocalStackContainer`를 사용해 테스트를 진행하는 게 좋을지 의견을 구하고 싶습니다!

2024-03-05 10:39 UTC, jhsseonn requested changes
s3 연동 고생 많으셨습니다!
다만 기본 이미지 설정 관련해서 회의에서 기본 이미지 설정은 하지 않고 null로 저장하는 것으로 정했기에 수정이 필요할 것 같아 rc로 남겨두었습니다.
그리고 질문이 있어 코멘트 남겨주시면 감사하겠습니다!
아래는 질문 주신 내용에 대한 답변입니다.

1. 기본 이미지 관련해서는 회의에서 논의한대로 null값으로 저장하는 것으로 수정하면 좋을 것 같습니다.
2. 테스트 속도가 조금 느리긴 하나 지금 당장 불편함을 느끼진 못해서 아직까진 수정이 필요하다는 생각이 들진 않습니다. 추후에 테스트가 많아져서 불편함이 체감될 정도가 되었을 때 수정해도 무방할 것 같습니다. 정수님 생각은 어떠신가요?

2024-03-05 10:39 UTC, jhsseonn commented on src/main/java/com/backend/blooming/user/presentation/UserController.java
> +            @RequestPart(required = false) final MultipartFile profileImage
질문입니다! 
프로필 이미지는 수정하지 않았을 경우에 대해  null 값으로 받기 위해 `@RequestPart`에 `required=false` 설정을 해준 것으로 이해했는데 그렇다면 이미지 수정을 하지 않은 경우와 기본 이미지로 설정하고자 하는 경우를 어떻게 구분할지도 궁금합니다! (혹시나 제가 아직 이미지 수정 요청/응답을 주고받는 것에 이해가 부족한 것인가 해서 질문드립니다!)

2024-03-05 10:39 UTC, jhsseonn commented on src/test/java/com/backend/blooming/user/domain/UserTest.java
> +                          .isEqualTo("https://dp7ped0142moi.cloudfront.net/default/profile.png");
마찬가지로 기본 이미지 설정 부분이라 수정이 필요할 것 같습니다!

2024-03-05 10:39 UTC, jhsseonn commented on src/test/java/com/backend/blooming/user/domain/UserTestFixture.java
> +    protected final String 기존_프로필_이미지_url = "https://original.profile.image";
마찬가지로 기본 이미지 설정 부분이라 수정이 필요할 것 같습니다!

2024-03-09 09:58 UTC, JJ503 commented on src/main/java/com/backend/blooming/user/domain/User.java
> +    }
혹시 몰라 일단 컨벤션에 따라 `""`로 수정했습니다.
url이 없을 시 `""`로 보내도 클라이언트 측에서 처리가 간편하다면 해당 방식으로 진행하고, 불편하시다면 null로 변경하도록 하겠습니다!

2024-03-09 10:01 UTC, JJ503 commented on src/main/java/com/backend/blooming/user/presentation/UserController.java
> +            @RequestPart(required = false) final MultipartFile profileImage
당시 진행할 때는 기본 이미지에 대해 고민하지 않고 진행했습니다.
또한, 기본 이미지로 변경한다는 것은 이미지를 없애겠다는 의미기에 수정 시 전달할 파일도 없고요!
그런데, 기본 이미지로 변경하는 것도 이번 pr에서 추가하면 좋을 것 같아 로직을 조금 수정했습니다.
`UserController`는 동일하게 진행하고 `UpdateUserRequest`에 `changeToDefaultProfile`이라는 boolean 타입의 변수를 추가했습니다.
기본 이미지로 설정하기를 원할 시 이를 true로 전달하면 좋을 것 같다고 생각했는데 어떠신가요?
위 방식 혹은 기본 이미지로 변경하는 것에 대한 추가적인 url이 있어야 한다고 생각했고, 그 중 위 방식으로 진행해보았습니다.
혹시 더 좋은 아이디어가 있다면 공유해주시면 감사하겠습니다!

2024-03-13 01:45 UTC, jhsseonn commented on src/main/java/com/backend/blooming/user/presentation/UserController.java
> +            @RequestPart(required = false) final MultipartFile profileImage
boolean 타입 변수로 기본 이미지로 변경여부를 전달해주는 방식 좋은 것 같습니다!

2024-03-13 01:46 UTC, jhsseonn approved these changes
수정사항 모두 확인했습니다! 머지하셔도 좋을 것 같습니다!

2024-03-16 07:22 UTC, merged