Flyway 적용
Goal-Tracker/blooming-backend pull request #95
Opened 2024-03-28 15:16 UTC by JJ503

- closed  #89

2024-03-30 07:12 UTC, jhsseonn requested changes
flyway 적용 고생 많으셨습니다!
스탬프 메시지 글자수 제한이 있어서 이 부분만 수정해주시면 감사하겠습니다.
그리고 GoalTeam에서 foreignKey명이 user와 goal이 반대로 되어 있는걸 이제야 발견했네요... 
이 부분은 수정하는 것이 좋을 것 같아 저도 이슈 파서 빠르게 수정하도록 하겠습니다.

2024-03-30 07:12 UTC, jhsseonn commented on src/main/resources/db/migration/V1.0__init_table.sql
> +    message                 text         not null,
스탬프 메시지 30자 제한 있어서 varchar(30)으로 제한 두는 것이 좋을 것 같습니다!

2024-03-30 07:12 UTC, jhsseonn commented on src/main/resources/db/migration/V1.0__init_table.sql
> +    add constraint fk_goal_team_goal foreign key (user_id) references users (id);
이 부분 반대로 되어 있어서 코드 확인해보니 반대로 적어두었네요... 수정하는 것이 좋을 것 같습니다! 저도 이 부분 빠르게 수정해서 올리도록 하겠습니다..!

2024-03-31 01:16 UTC, JJ503 commented on src/main/resources/db/migration/V1.0__init_table.sql
> +    message                 text         not null,
도메인에서 message가 text로 설정되어 있었어 varchar(30)으로 수정하는 것도 함께 진행했습니다.

2024-03-31 03:21 UTC, jhsseonn approved these changes
변경사항 모두 확인했습니다. approve 하겠습니다!

2024-03-31 11:02 UTC, merged