골 참여자 방출 기능 구현
Goal-Tracker/blooming-backend pull request #99
Opened 2024-03-29 17:41 UTC by jhsseonn

**3/30**
골 참여자 방출 기능 구현 완료했습니다.
두가지 논의사항이 있어 질문 드립니다. 논의가 필요한 코드 윗줄에 TO DO로 주석 남겨놓아서 쉽게 찾아보실 수 있을 것 같습니다.

[논의사항]
1. 참여자 방출시 해당 참여자의 모든 스탬프를 삭제하는 로직을 stampService에서 구현하고 해당 메서드를 goalService에서 참여자를 방출할 때 호출하는 방식으로 구현했는데, goalService의 골 참여자 방출 메서드에서 한꺼번에 구현하는 것이 나을까요? stmapService로 로직을 분리한 이유는 스탬프 삭제 로직은 스탬프 서비스에 존재하는 것이 역할상 더 적절하다고 생각했습니다.
2. 골 참여자 방출 api 형식을 /goals/{goalId}/user/{userId} 로 지정했는데, /user 부분이 꼭 필요없을까요? 프론트에서 api를 호출할 때 /user를 넣는 것이 더 구분하기 쉬울 수도 있겠다는 생각에 우선 넣었습니다.

[작업 내용]
- 골 참여자 방출 서비스 및 컨트롤러 기능 구현
- 골 참여자 방출 시 참여자의 모든 스탬프 삭제
- Exception 클래스명 변경(클래스명 통일을 위해 리팩터링 했습니다.)
- closed #90 

p.s. 이슈번호 잘못 보고 브랜치 파는 바람에 브랜치를 다시 팠습니다.. 다음엔 확실히 확인하도록 하겠습니다..

2024-03-30 14:05 UTC, JJ503 requested changes
기능 구현하시느라 고생 많으셨습니다!
몇 가지 질문들이 있어 일단 rc로 처리해 두었습니다.
논의 사항에 대한 답변은 각 TODO 코드 쪽에 코멘트 달아두었습니다.
의견을 정리하자면 현재 상태가 좋다입니다!

2024-03-30 14:05 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Teams.java
> +        });
개인적으로 아래와 같은 for문을 통해 break를 추가하면 어떨까 하는 생각이 있습니다.
현재는 물론 최대 5명이기에 상관없긴 하지만, 팀원이 많아질 수 있다면 결국 성능상 아주 조금은 낮아지지 않을까 해서요!
물론 정말 완벽한 성능 개선을 생각한다면 좀 더 고민해 봐야 하긴 하지만요...ㅎㅎ

```suggestion
        for (GoalTeam goalTeam : goalTeams) {
            if (goalTeam.getUser().getId().equals(userId)) {
                goalTeam.updateDeleted();
                break;
            }
        }
```

2024-03-30 14:10 UTC, JJ503 commented
갑자기 생각이 나 코멘트 추가합니다.
현재 방출에 대한 api 응답 값은 no-content입니다.
그런데, 팀원 삭제에 따라 팀 목록과 스탬프 정보들이 달라지는 데 이 부분은 어떻게 다시 받아오나요?
수정 파트에서 골, 팀원 정보를 위해 추가 api 요청은 없는 것으로 알고, 현재 상태라면 수정 탭을 닫으면 fragment를 닫는 것으로 이해해 골 조회 api를 요청하지 않을 것 같아 여쭤봅니다!
제가 현재 골과 관련해 안드로이드와 어떻게 요청이 오가는지 완벽히 이해하지 못해 드리는 질문 같기도 합니다..!

2024-04-03 13:07 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/application/StampService.java
> +    }
좋습니다! 그러면 지금은 일단 이렇게 두고, 의존성 관련 리팩터링에 대한 논의 후에 정해진 대로 리팩터링 하는 것으로 해요!

2024-04-03 13:50 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Teams.java
> +    }
이렇게 하면 삭제된 사용자는 불러와지지 않습니다. updateGoalTeams를 하지 않을 경우, 삭제된 사용자가 그대로 goalTeams에 남아있기 때문에 삭제를 하지 않은 사용자들만 다시 goalTeams에 할당했습니다. 그런데 너무 어렵게 생각한 것 같네요.. 정수님이 밑에서 피드백 주신대로 for문 돌면서 if문 걸리면 delete하고 goalTeams에서도 remove 하는 방식으로 수정했습니다!

softDelete vs hardDelete 관련해서는 골 팀은 hardDelete를 해도 문제가 없을 것 같아요. 정말 단지 골 참여자 목록에 추가하기 위해 만들어진 테이블이기 때문에 소속 되어있던 골에서 방출되면 더 이상 테이블의 존재 의미가 없어지긴 합니다. 추후 분석용 데이터로서는 어느정도 의미가 있을까요? 딱히 생각나는 활용방안이 없어서 저는 hardDelete를 해도 좋을 것 같습니다.

2024-04-03 14:16 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/application/GoalService.java
> +    public void deleteUser(final Long userId, final Long goalId, final Long managerId) {
좋습니다! managerId를 userId로 바꾸고 현 userId를 deleteUserId로 바꾸는 게 좋은 것 같네요!

2024-04-03 14:31 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Teams.java
> +        });
위에서 코멘트 남긴대로 for문 돌다가 if문에서 걸리면 goalTeam delete 해주고 Teams에서는 remove해주는 식으로 구현했습니다. 감사합니다!

2024-04-03 14:58 UTC, jhsseonn commented
브랜치 최신화 관련해서 질문이 있습니다...!
저번에 브랜치 꼬였을 때 develop 브랜치 update project해서 해당 브랜치를 그대로 머지하면 develop 브랜치 커밋 내역이 그대로 딸려와서 rebase로 최신화를 해주었는데 똑같이 커밋 내역이 그대로 따라오더라구요... 
혹시 커밋내역 안 따라오게 rebase 하는 법을 아실까요?

2024-04-07 02:50 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Teams.java
> +    }
hardDelete를 해도 괜찮을 것 같습니다.
원래 해당 리뷰를 작성할 때 팀원 정보가 스탬프에 영향을 주지 않을까 했었는데, user를 fk로 사용하고 있어 큰 문제가 없을 것 같습니다.
그래서 결론적으로는 hardDelete로 하면 좋을 것 같네요!

2024-04-07 02:54 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Teams.java
> +    }
그런데 현재는 soft delete 처리로 되어 있는 것 같은데 맞을까요?

2024-04-07 03:00 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
> +                                            .toList();
테스트 클래스에는 `@Transactional`을 붙이지 않기에 전이가 되지 않는 것이 맞습니다.
그래서 만약 해당 테스트를 수행했을 것이라면, `deleteUser` 수행 후 `goalRepository`를 통해 다시 조회해 가져오는 것이 적절헀을 것이라 생각합니다!
이와 관련해 해당 클래스 157번째 라인인 `요청받은_골의_아이디에_해당하는_골을_삭제한다`에 대해 예외가 일어나지 않는다가 아니라, 해당 서비스 메서드 수행 후 `goalRepository`에서 해당 골을 조회할 때 `optional`의 `isEmpty()`로 테스트를 수행하는 것은 어떨까요?
테스트하고자 하는 바를 명확히 하는 것이 좋을 것 같아 제안드립니다!

2024-04-07 03:05 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
> +    public boolean isDeletedFalse() {
저는 오히려 동일한 로직이 추가되어 코드의 중복이 발생하는 것이 아닌가 하는 의문이 있습니다.

또한, 해당 메서드를 사용할 것이라면 `isNotDeleted()`는 어떨까요?
`GoalTeams` 객체 외부에서는 deleted가 boolean 타입인지 다른 타입인지 알 필요가 없다고 생각합니다.

2024-04-07 03:09 UTC, JJ503 commented
rebase가 아닌 merge를 해야 합니다!
rebase 하게 되는 경우 머지를 하는 대상에 대한 커밋 해시가 새로 생성되어 기존 브랜치에 있는 커밋 내역과 다른 커밋으로 인지하는 것으로 알고 있습니다.
그래서 merge를 해줘야 하는데, 꼬였다는 게 정확히 어떤 의미인지 알 수 없어 좀 더 자세한 설명 혹은 게더를 통해 확인하는 것이 좋을 것 같습니다.

2024-04-19 12:45 UTC, jhsseonn commented on src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
> +                                            .toList();
말씀주신 방식이 테스트 목적을 더 잘 반영할 것 같네요! 이렇게 수정하도록 하겠습니다!

2024-04-19 13:32 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/Teams.java
> +    }
hardDelete로 구현하기로 결정된 게 아니라고 판단해 로직을 추가하지 않았습니다. 로직 추가해서 리뷰 재요청하도록 하겠습니다.

2024-05-03 14:00 UTC, jhsseonn commented on src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
> +    public boolean isDeletedFalse() {
고민해봤는데 isDeletedFalse 자체가 굳이 필요하지 않은 메서드를 만든 것 같아 삭제하고 isDeleted의 True/False 여부 확인으로 수정했습니다!

2024-05-07 15:56 UTC, JJ503 approved these changes
수정하신 사항들 모두 확인 완료했습니다!
수정하시느라 고생 많으셨습니다.
질문 사항 및 기록용 코멘트 남겨두었습니다. 머지 전에 한 번 확인해주시면 감사하겠습니다!

2024-05-07 15:56 UTC, JJ503 commented on src/main/java/com/backend/blooming/goal/domain/Teams.java
> +        goalTeams.removeIf(goalTeam -> goalTeam.getUser().equals(user));
👍👍👍

2024-05-07 15:56 UTC, JJ503 commented on src/main/java/com/backend/blooming/stamp/infrastructure/repository/StampRepository.java
> +    List<Stamp> findAllByGoalIdAndUserId(final Long goalId, final Long userId);
jpa 네이밍만으로 안 되기에 쿼리문을 사용한 것이 맞을까요?
궁금해서 여쭤봅니다!

2024-05-07 15:56 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/domain/GoalTest.java
> +                                             .toList();
해당 부분은 `assertSofly` 밖에 작성해줘도 좋을 것 같네요!
오히려 테스트하고자 하는 부분이 잘 안 보여서요.

2024-05-07 15:56 UTC, JJ503 commented on src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
> +        final ReadGoalDetailDto result = goalService.deleteUser(방출할_사용자_아이디, 유효한_골_아이디, 유효한_사용자_아이디);
저희 테스트하고자 하는 객체에 대한 필드명은 `acutal`로 하기로 했던 것으로 기억합니다!

2024-05-20 05:22 UTC, jhsseonn commented on src/main/java/com/backend/blooming/stamp/infrastructure/repository/StampRepository.java
> +    List<Stamp> findAllByGoalIdAndUserId(final Long goalId, final Long userId);
네 맞습니다! 네이밍만으로 조회가 불가하다고 판단해 쿼리문 사용했습니다!

2024-05-20 05:44 UTC, merged